import type { LessonOutline } from "./course-types";

export const defaultLessonOutlines: LessonOutline[] = [
  {
    n: "01",
    title: "An toàn và làm quen nước",
    meta: "Nền tảng · 45 phút",
    status: "Bài hoàn chỉnh",
    group: "Nền tảng bắt buộc",
    summary: "Hình thành thói quen an toàn, kiểm soát thở và bình tĩnh xử lý các tình huống cơ bản trước khi học kỹ thuật.",
    duration: "45 phút",
    target: "Thực hiện đúng toàn bộ quy tắc an toàn và hoàn thành ba nhiệm vụ làm quen nước có người giám sát.",
    objectives: [
      "Nhận biết khu vực tập phù hợp, độ sâu an toàn và vai trò của người giám sát.",
      "Thực hiện vào – ra bể đúng cách, thở ra dưới nước và đứng dậy về tư thế an toàn.",
      "Giữ bình tĩnh khi nước vào mặt; biết dừng tập khi đau, chóng mặt, khó thở hoặc chuột rút.",
    ],
    core: [
      { title: "Kiểm tra trước buổi tập", body: "Sức khỏe, khu vực bơi, độ sâu, thành bể, dụng cụ và người giám sát." },
      { title: "Kiểm soát hô hấp", body: "Hít vào trên mặt nước; úp mặt và thở ra đều, không cố nín thở kéo dài." },
      { title: "Tư thế hồi phục", body: "Thu gối, đặt chân xuống đáy ở vùng nước nông và đứng dậy có kiểm soát." },
      { title: "Quy tắc dừng", body: "Dừng ngay khi xuất hiện đau, hoảng loạn, chóng mặt, khó thở hoặc mất kiểm soát." },
    ],
    practice: ["Vào và ra bể bằng thành bể", "Thổi khí dưới nước 5–8 lần", "Nổi có hỗ trợ rồi đứng dậy", "Di chuyển sát thành bể"],
    pass: ["Không tập một mình", "Thực hiện đúng ba thao tác an toàn liên tiếp", "Giữ được nhịp thở bình tĩnh"],
    bridge: "Đủ nền tảng để chuyển sang tư thế thân người và lướt nước.",
  },
  {
    n: "02",
    title: "Tư thế thân người và lướt",
    meta: "Kỹ thuật cơ bản · 60 phút",
    status: "Bài hoàn chỉnh",
    group: "Nền tảng kỹ thuật",
    summary: "Tạo một đường thân dài, cân bằng và ít lực cản để mọi động tác tay – chân phía sau đều có hiệu quả.",
    duration: "60 phút",
    target: "Lướt sấp tối thiểu 5 m với thân cân bằng, đầu đúng vị trí và không vội cử động tay chân.",
    objectives: [
      "Giải thích được vai trò của lực nổi, lực cản và diện tích cản phía trước.",
      "Giữ đầu giữa hai tay, mắt nhìn chếch xuống, thân kéo dài và hông gần mặt nước.",
      "Tự đứng dậy an toàn sau pha lướt ở vùng nước phù hợp.",
    ],
    core: [
      { title: "Đường thân", body: "Đầu, vai, hông và chân tạo thành một đường dài theo hướng tiến." },
      { title: "Vị trí đầu", body: "Không ngẩng cao; mắt nhìn chếch xuống để hạn chế hông và chân chìm." },
      { title: "Tư thế hai tay", body: "Hai tay duỗi ra trước, khép tự nhiên và tạo hình dạng gọn khi lướt." },
      { title: "Kết thúc pha lướt", body: "Đứng dậy khi vận tốc giảm rõ, không cố lướt đến mất kiểm soát." },
    ],
    practice: ["Nổi sấp có hỗ trợ", "Đẩy thành bể và lướt 3–5 m", "Lướt qua mốc cố định", "Lướt rồi đứng dậy"],
    pass: ["Lướt tối thiểu 5 m", "Đầu không ngẩng cao", "Đứng dậy bình tĩnh và đúng trình tự"],
    bridge: "Tư thế lướt là điểm bắt đầu và kết thúc của mỗi chu kỳ chân.",
  },
  {
    n: "03",
    title: "Kỹ thuật chân bơi ếch",
    meta: "Bài chuẩn vàng · 60 phút",
    status: "Bài hoàn chỉnh",
    group: "Kỹ thuật cốt lõi",
    summary: "Học chu kỳ thu – bẻ – đạp khép – lướt để tạo lực tiến bằng hai chân đồng thời và hạn chế lực cản.",
    duration: "60 phút",
    target: "Đạt tối thiểu 8/10 và thực hiện được 10 m đạp chân có kiểm soát, không có lỗi an toàn nghiêm trọng.",
    objectives: ["Mô tả đúng bốn pha", "Thực hiện hai chân đồng thời", "Nhận diện ít nhất ba lỗi thường gặp"],
    core: [
      { title: "Thu chân", body: "Gót về gần mông, gối mở vừa phải." },
      { title: "Bẻ bàn chân", body: "Gập cổ chân và xoay mũi chân ra ngoài." },
      { title: "Đạp – khép", body: "Đẩy nước ra sau, quét vào trong và khép kín." },
      { title: "Duỗi – lướt", body: "Hai chân khép, thân dài và giữ vận tốc." },
    ],
    practice: ["Mô phỏng trên cạn", "Bám thành bể", "Đạp nằm ngửa", "Một đạp – một lướt"],
    pass: ["Đạt tối thiểu 8/10", "Hai chân chuyển động đồng thời", "Hoàn thành 10 m có kiểm soát"],
    bridge: "Khi chân đã ổn định, người học chuyển sang kỹ thuật quạt tay.",
  },
  {
    n: "04",
    title: "Kỹ thuật tay",
    meta: "Kỹ thuật cơ bản · 60 phút",
    status: "Bài hoàn chỉnh",
    group: "Kỹ thuật cốt lõi",
    summary: "Nắm bốn giai đoạn của động tác tay: tách tay tỳ nước, quạt nước, thu tay và duỗi tay về trước.",
    duration: "60 phút",
    target: "Đạt tối thiểu 8/10 và thực hiện liên tục 8 chu kỳ tay đúng đường đi, không quạt quá rộng hoặc kéo khuỷu tay ra sau vai.",
    objectives: [
      "Mô tả đúng bốn giai đoạn và mục đích của từng giai đoạn.",
      "Cảm nhận được áp lực nước ở bàn tay và cẳng tay khi bắt đầu quạt.",
      "Thu tay nhanh gọn và duỗi về trước để trở lại tư thế lướt.",
    ],
    core: [
      { title: "Tách tay tỳ nước", body: "Bàn tay xoay ra ngoài và chếch xuống đến khi cảm nhận được áp lực nước." },
      { title: "Quạt nước", body: "Bàn tay và cẳng tay chuyển động ra sau; tay không kéo vượt quá trục vai." },
      { title: "Thu tay", body: "Hai khuỷu khép dần, bàn tay chuyển vào trong, lên trên và về trước." },
      { title: "Duỗi tay", body: "Hai tay duỗi nhanh về trước, lòng bàn tay xoay dần úp xuống để chuẩn bị lướt." },
    ],
    practice: ["Mô phỏng tay trước gương", "Đứng nước nông cảm nhận tỳ nước", "Quạt tay kẹp phao giữa chân", "Tám chu kỳ tay có đếm nhịp"],
    pass: ["Đúng thứ tự bốn giai đoạn", "Không kéo tay quá vai", "Tám chu kỳ liên tục có kiểm soát", "Đạt tối thiểu 8/10"],
    bridge: "Động tác tay tạo thời điểm phù hợp để đưa miệng lên mặt nước và hít vào.",
  },
  {
    n: "05",
    title: "Kỹ thuật thở",
    meta: "Phối hợp · 60 phút",
    status: "Bài hoàn chỉnh",
    group: "Kỹ thuật phối hợp",
    summary: "Đưa hô hấp vào đúng nhịp tay, tránh ngẩng đầu quá cao và giữ dòng thở ra ổn định khi mặt trở lại nước.",
    duration: "60 phút",
    target: "Đạt tối thiểu 8/10 và thực hiện 8 chu kỳ tay – thở liên tục, mỗi chu kỳ một lần hít vào mà không mất tư thế thân người.",
    objectives: [
      "Hít vào bằng miệng khi vai và miệng lên khỏi mặt nước.",
      "Thở ra đều khi mặt ở dưới nước; không cố giữ hơi quá lâu.",
      "Giữ cằm gần mặt nước, tránh ngẩng đầu khiến hông và chân chìm.",
    ],
    core: [
      { title: "Thời điểm hít vào", body: "Hít vào trong pha quạt – thu tay khi miệng vừa lên khỏi mặt nước." },
      { title: "Thời điểm thở ra", body: "Bắt đầu thở ra khi tay duỗi và thân trở lại tư thế lướt." },
      { title: "Vị trí đầu", body: "Đầu đi theo chuyển động tự nhiên của vai, không hất cằm lên cao." },
      { title: "Nhịp cơ bản", body: "Một chu kỳ tay đi với một lần hít vào; ưu tiên đều và bình tĩnh." },
    ],
    practice: ["Thở tại thành bể", "Tay – thở khi đứng nước nông", "Quạt tay có phao hỗ trợ", "Tám nhịp tay – thở liên tục"],
    pass: ["Một chu kỳ một lần thở", "Không ngẩng đầu quá cao", "Tám chu kỳ không hoảng loạn hoặc hụt hơi", "Đạt tối thiểu 8/10"],
    bridge: "Sau khi tay và thở ổn định, ghép thêm động tác chân theo đúng khoảng nghỉ.",
  },
  {
    n: "06",
    title: "Phối hợp hoàn chỉnh",
    meta: "Tổng hợp · 60 phút",
    status: "Bài hoàn chỉnh",
    group: "Kỹ thuật tổng hợp",
    summary: "Ghép tay, chân và thở thành một chu kỳ có trật tự rõ: quạt – thở – thu – đạp – lướt.",
    duration: "60 phút",
    target: "Đạt tối thiểu 8/10 và bơi liên tục 25 m với nhịp ổn định, có pha lướt rõ, không để tay – chân cùng tạo lực sai thời điểm.",
    objectives: [
      "Mô tả đúng trình tự phối hợp một chu kỳ hoàn chỉnh.",
      "Giữ chân duỗi khi tay bắt đầu tỳ và quạt nước.",
      "Đạp chân khi tay đã duỗi về trước, sau đó giữ một khoảng lướt hợp lý.",
    ],
    core: [
      { title: "Tỳ – quạt – hít vào", body: "Tay bắt đầu tạo lực, chân vẫn duỗi và miệng lên lấy hơi." },
      { title: "Thu tay – thu chân", body: "Tay khép gọn về trước trong khi gót bắt đầu thu về." },
      { title: "Duỗi tay – đạp chân", body: "Tay trở về đường thân trước khi chân tạo lực ra sau." },
      { title: "Khép – lướt – thở ra", body: "Cơ thể thuôn dài, giữ vận tốc rồi mới bắt đầu chu kỳ mới." },
    ],
    practice: ["Tay trước – chân sau trên cạn", "Hai tay một chân có đếm nhịp", "Một chu kỳ – một lần lướt", "Bơi 4 lượt × 25 m"],
    pass: ["Đúng thứ tự phối hợp", "Có pha lướt rõ", "Hoàn thành 25 m với nhịp ổn định", "Đạt tối thiểu 8/10"],
    bridge: "Bài tiếp theo dùng quan sát và bài tập bổ trợ để sửa lỗi còn lại trong chu kỳ hoàn chỉnh.",
  },
  {
    n: "07",
    title: "Lỗi sai và cách sửa",
    meta: "Củng cố · 60 phút",
    status: "Bài hoàn chỉnh",
    group: "Củng cố kỹ thuật",
    summary: "Chuyển từ cảm giác “bơi chưa tốt” thành dấu hiệu quan sát được, nguyên nhân có thể kiểm tra và một bài tập sửa cụ thể.",
    duration: "60 phút",
    target: "Đạt tối thiểu 8/10, tự nhận diện đúng hai lỗi ưu tiên qua quan sát hoặc đoạn ghi hình và cải thiện ít nhất một lỗi sau ba lượt sửa.",
    objectives: [
      "Phân biệt lỗi tư thế, lỗi chân, lỗi tay, lỗi thở và lỗi phối hợp.",
      "Xác định một nguyên nhân chính thay vì sửa nhiều chi tiết cùng lúc.",
      "Thực hiện trình tự sửa: trên cạn – bám thành – di chuyển ngắn – kiểm tra lại.",
    ],
    core: [
      { title: "Quan sát", body: "Ghi nhận biểu hiện cụ thể: gối quá rộng, tay quá vai, đầu ngẩng cao hoặc mất pha lướt." },
      { title: "Chọn lỗi ưu tiên", body: "Ưu tiên lỗi an toàn, sau đó đến lỗi làm tăng cản hoặc phá nhịp." },
      { title: "Chọn bài tập", body: "Mỗi bài tập chỉ phục vụ một tín hiệu sửa rõ ràng và có số lần kiểm tra." },
      { title: "Đánh giá lại", body: "So sánh trước – sau bằng mốc khoảng cách, số chu kỳ hoặc đoạn ghi hình ngắn." },
    ],
    practice: ["Quan sát từ bên và phía sau", "Phiếu nhận diện lỗi", "Ba lượt sửa một lỗi", "So sánh trước – sau"],
    pass: ["Gọi tên đúng hai lỗi", "Chọn đúng bài tập bổ trợ", "Cải thiện được ít nhất một dấu hiệu", "Đạt tối thiểu 8/10"],
    bridge: "Kết quả sửa lỗi được đưa vào giáo án bốn tuần để duy trì tiến bộ.",
  },
  {
    n: "08",
    title: "Giáo án luyện tập",
    meta: "Ứng dụng · 4 tuần",
    status: "Bài hoàn chỉnh",
    group: "Ứng dụng và duy trì",
    summary: "Sắp xếp các kỹ thuật đã học thành kế hoạch bốn tuần, có mục tiêu buổi tập, khối lượng vừa sức và mốc đánh giá rõ.",
    duration: "4 tuần",
    target: "Đạt tối thiểu 8/10, hoàn thành ít nhất 6 buổi có ghi chép và vượt bài đánh giá cuối: 25 m đúng nhịp, an toàn, kiểm soát được hô hấp.",
    objectives: [
      "Biết cấu trúc một buổi tập: khởi động, kỹ thuật, ghép nhịp, hồi tĩnh và ghi chép.",
      "Tăng khối lượng theo chất lượng động tác, không tăng chỉ vì đã đủ số buổi.",
      "Dùng kết quả từng tuần để chọn kỹ thuật cần củng cố ở tuần tiếp theo.",
    ],
    core: [
      { title: "Tuần 1 · Nền tảng", body: "An toàn, thở, nổi, lướt và nhắc lại tư thế thân người." },
      { title: "Tuần 2 · Kỹ thuật riêng", body: "Củng cố chân, tay và thở bằng các đoạn ngắn có nghỉ." },
      { title: "Tuần 3 · Ghép nhịp", body: "Tăng dần số chu kỳ hoàn chỉnh, giữ rõ pha lướt." },
      { title: "Tuần 4 · Ổn định", body: "Sửa lỗi ưu tiên, bơi 25 m và đánh giá bằng tiêu chí đã khóa." },
    ],
    practice: ["Sáu đến tám buổi có người giám sát", "Ghi một lỗi ưu tiên mỗi buổi", "Theo dõi số chu kỳ trên 25 m", "Đánh giá cuối bốn tuần"],
    pass: ["Đạt tối thiểu 8/10", "Hoàn thành ít nhất 6 buổi", "Bơi 25 m đúng trình tự", "Không vi phạm quy tắc an toàn"],
    bridge: "Hoàn tất lộ trình cơ bản và chuyển sang giai đoạn luyện ổn định quãng đường dài hơn.",
  },
];
