import type { FoundationDetail } from "./course-types";

export const foundationDetails: Record<"01" | "02" | "04" | "05" | "06" | "07" | "08", FoundationDetail> = {
  "01": {
    safety: {
      title: "Không xuống nước một mình",
      body: "Chỉ tập tại khu vực được phép, biết rõ độ sâu và có người giám sát đủ năng lực. Xuống nước bằng chân ở vị trí dành cho người bơi; không lao đầu xuống nơi chưa được xác nhận an toàn.",
    },
    knowledge: [
      {
        title: "Kiểm tra trước khi xuống nước",
        body: "Một buổi tập an toàn bắt đầu từ việc quan sát môi trường và tự đánh giá tình trạng cơ thể.",
        steps: ["Xác định độ sâu, lối xuống, lối lên và vị trí cứu hộ.", "Báo mục tiêu buổi tập cho người giám sát.", "Khởi động nhẹ khớp vai, hông, gối và cổ chân."],
        cue: "Biết nơi tập · biết người giám sát · biết lối ra",
        avoid: "Không xuống nước khi đang choáng, khó thở, đau bất thường hoặc mất tỉnh táo.",
      },
      {
        title: "Vào và ra bể có kiểm soát",
        body: "Người mới học ưu tiên cầu thang hoặc tư thế ngồi xoay người vào bể, luôn duy trì điểm tựa chắc chắn.",
        steps: ["Ngồi sát mép hoặc dùng cầu thang đúng chiều.", "Đưa từng chân xuống nước, tay bám chắc thành bể.", "Khi ra bể, quay mặt vào thành và dùng tay nâng thân lên từng bước."],
        cue: "Chân xuống trước · tay luôn có điểm tựa",
        avoid: "Không chạy trên nền ướt, nhảy tùy tiện hoặc quay lưng sát mép bể.",
      },
      {
        title: "Hít trên mặt nước, thở dưới nước",
        body: "Mục tiêu đầu tiên không phải nín thở lâu mà là tạo một vòng hô hấp bình tĩnh và có kiểm soát.",
        steps: ["Hít vào vừa đủ bằng miệng khi mặt ở trên nước.", "Úp mặt từ từ và thở ra liên tục bằng mũi hoặc cả mũi và miệng.", "Ngẩng lên khi gần hết hơi, nghỉ rồi lặp lại."],
        cue: "Hít vừa · úp mặt · thở đều",
        avoid: "Không thi nín thở, không cố giữ hơi đến khó chịu hoặc hoảng loạn.",
      },
      {
        title: "Nổi có hỗ trợ và đứng dậy",
        body: "Đứng dậy đúng trình tự giúp người học kết thúc mỗi bài nổi hoặc lướt mà không bị cuống.",
        steps: ["Hai tay bám dụng cụ hoặc tay người hướng dẫn, mặt úp và thân thả lỏng.", "Khi cần đứng, thu gối về gần bụng và kéo hai tay xuống.", "Đặt hai chân xuống đáy, nâng đầu sau khi bàn chân đã có điểm tựa."],
        cue: "Thu gối · chân chạm đáy · rồi mới ngẩng",
        avoid: "Không giật đầu lên trước vì chân dễ chìm và cơ thể mất thăng bằng.",
      },
      {
        title: "Xử lý khi mất bình tĩnh",
        body: "Ưu tiên giữ đường thở, tìm điểm bám và báo hiệu thay vì cố vùng vẫy hoặc bơi tiếp.",
        steps: ["Dừng động tác mạnh, quay về phía thành bể hoặc vật nổi gần nhất.", "Bám chắc, thở chậm và báo cho người giám sát.", "Nếu thấy người khác gặp nạn, gọi cứu hộ và đưa vật nổi từ vị trí an toàn."],
        cue: "Dừng · bám · thở · gọi hỗ trợ",
        avoid: "Không tự lao xuống cứu người nếu chưa được huấn luyện cứu hộ dưới nước.",
      },
    ],
    drills: [
      { code: "1.1", title: "Nhận diện khu vực tập", goal: "Biết ranh giới an toàn trước khi xuống nước", steps: ["Chỉ độ sâu", "Chỉ lối lên gần nhất", "Chỉ vị trí người giám sát"], volume: "2 lượt kiểm tra", pass: "Gọi đúng cả ba vị trí", safety: "Thực hiện khi còn ở trên bờ" },
      { code: "1.2", title: "Vào – ra bể bằng điểm tựa", goal: "Chuyển tư thế chậm và chắc", steps: ["Ngồi hoặc dùng cầu thang", "Chân xuống trước", "Ra bể khi vẫn quay mặt vào thành"], volume: "3 lần liên tiếp", pass: "Không trượt, không buông điểm tựa", safety: "Người giám sát đứng trong tầm với" },
      { code: "1.3", title: "Thổi khí tại thành bể", goal: "Tạo nhịp hít – thở bình tĩnh", steps: ["Hít vừa", "Úp mặt", "Thở ra đến khi bọt khí đều"], volume: "2 lượt × 5 lần", pass: "Năm lần liên tiếp không nín giữ", safety: "Hai tay luôn bám thành" },
      { code: "1.4", title: "Nổi sấp có hỗ trợ", goal: "Cảm nhận lực nổi và thả lỏng", steps: ["Duỗi thân", "Thở ra nhẹ", "Thu gối và đứng dậy"], volume: "5 lần", pass: "Tự kết thúc đúng trình tự 4/5 lần", safety: "Chỉ tập ở vùng nước nông" },
      { code: "1.5", title: "Di chuyển sát thành bể", goal: "Biết quay về điểm an toàn", steps: ["Hai tay thay nhau bám", "Di chuyển ngang", "Dừng và ra hiệu"], volume: "2 lượt × 5 m", pass: "Không mất điểm bám", safety: "Không vượt khỏi khu vực đã thống nhất" },
    ],
    mistakes: [
      { sign: "Nín thở rồi bật đầu lên gấp", cause: "Chưa quen thở ra khi mặt ở dưới nước", fix: "Giảm thời gian úp mặt; ưu tiên bọt khí đều thay vì ở lâu." },
      { sign: "Đứng dậy bằng cách ngẩng đầu trước", cause: "Chưa nhớ trình tự thu gối và đặt chân", fix: "Tập riêng khẩu lệnh: thu gối – chân chạm đáy – ngẩng." },
      { sign: "Buông thành bể khi chưa sẵn sàng", cause: "Muốn chuyển bài quá nhanh", fix: "Giữ một tay bám cho đến khi thở và tư thế đã ổn định." },
      { sign: "Vùng vẫy khi nước vào mặt", cause: "Phản xạ hoảng và chưa có điểm bám", fix: "Tập dừng – bám – thở ở cự ly một cánh tay với thành bể." },
    ],
    session: [
      { time: "05′", title: "Kiểm tra an toàn", body: "Xác định độ sâu, lối ra, người giám sát và tín hiệu dừng." },
      { time: "07′", title: "Khởi động trên bờ", body: "Làm ấm khớp, tập nhịp hít vào và thở ra chậm." },
      { time: "08′", title: "Vào – ra bể", body: "Ba lần có điểm tựa chắc và người giám sát trong tầm với." },
      { time: "10′", title: "Làm quen mặt nước", body: "Thổi khí, úp mặt ngắn và tăng dần khi vẫn bình tĩnh." },
      { time: "10′", title: "Nổi rồi đứng dậy", body: "Nổi có hỗ trợ, thu gối, đặt chân và kết thúc đúng trình tự." },
      { time: "05′", title: "Củng cố", body: "Di chuyển sát thành, nhắc lại dừng – bám – thở – gọi hỗ trợ." },
    ],
    questions: [
      { q: "Điều kiện nào bắt buộc trước khi người mới xuống nước?", options: ["Có người giám sát và biết rõ khu vực tập", "Đã nín thở được một phút", "Có kính bơi mới", "Đã xem người khác bơi"], answer: 0, explain: "Người mới chỉ tập tại khu vực phù hợp, biết rõ độ sâu và có người giám sát đủ năng lực." },
      { q: "Cách vào nước phù hợp ở vị trí chưa được phép nhảy là gì?", options: ["Lao đầu xuống trước", "Chạy lấy đà", "Dùng cầu thang hoặc vào bằng chân có điểm tựa", "Nhảy lùi"], answer: 2, explain: "Vào bằng chân và có điểm tựa giúp kiểm soát tư thế, đặc biệt ở nơi nông hoặc chưa rõ điều kiện." },
      { q: "Trình tự đứng dậy sau khi nổi sấp là gì?", options: ["Ngẩng đầu – quạt tay – co chân", "Thu gối – đặt chân – nâng đầu", "Đạp mạnh – xoay người – đứng", "Nín thở – kéo tay – nhảy"], answer: 1, explain: "Thu gối và đặt chân xuống đáy trước giúp tạo điểm tựa rồi mới nâng đầu." },
      { q: "Khi mất bình tĩnh gần thành bể, nên làm gì trước?", options: ["Bơi nhanh hơn", "Vùng vẫy để nổi", "Dừng, bám và ổn định nhịp thở", "Lặn xuống đáy"], answer: 2, explain: "Dừng động tác mạnh, tìm điểm bám và lấy lại hô hấp là lựa chọn an toàn hơn." },
      { q: "Mục tiêu của bài thổi khí dưới nước là gì?", options: ["Nín thở càng lâu càng tốt", "Tạo nhịp hít trên mặt nước và thở ra đều dưới nước", "Thở vào khi mặt ở dưới nước", "Ngẩng đầu liên tục"], answer: 1, explain: "Người mới cần kiểm soát vòng hô hấp bình tĩnh, không thi nín thở hoặc giữ hơi đến khó chịu." },
      { q: "Dấu hiệu nào yêu cầu dừng buổi tập ngay?", options: ["Nước hơi mát", "Chưa bơi đủ số lượt", "Đau bất thường, chóng mặt hoặc khó thở", "Kính bơi bị mờ"], answer: 2, explain: "Đau, chóng mặt, khó thở, chuột rút hoặc hoảng loạn là các tín hiệu phải dừng và báo người giám sát." },
      { q: "Khi di chuyển sát thành bể, nguyên tắc quan trọng nhất là gì?", options: ["Luôn duy trì ít nhất một điểm bám", "Buông cả hai tay để đi nhanh", "Nhắm mắt để tập thăng bằng", "Di chuyển ra giữa làn"], answer: 0, explain: "Duy trì điểm bám giúp người mới luôn có đường quay về trạng thái an toàn." },
      { q: "Nếu thấy người khác gặp nạn, người chưa được huấn luyện nên làm gì?", options: ["Lao xuống ôm người đó", "Gọi cứu hộ và đưa vật nổi từ vị trí an toàn", "Bơi vòng quanh quan sát", "Chờ người đó tự vào bờ"], answer: 1, explain: "Cứu gián tiếp bằng cách gọi trợ giúp và đưa vật nổi tránh tạo thêm một nạn nhân." },
      { q: "Vì sao không nên chạy trên nền bể ướt?", options: ["Làm nước bắn lên", "Dễ trượt ngã và mất kiểm soát gần mép bể", "Làm ồn", "Nhanh mệt"], answer: 1, explain: "Nền ướt làm tăng nguy cơ trượt ngã, đặc biệt nguy hiểm sát mép nước." },
      { q: "Khẩu lệnh đầy đủ khi bất ổn trong nước là gì?", options: ["Đạp – quạt – nín – lao", "Dừng – bám – thở – gọi hỗ trợ", "Lặn – xoay – bơi – nhảy", "Ngẩng – quạt – đạp – chạy"], answer: 1, explain: "Dừng, tìm điểm bám, ổn định đường thở và gọi hỗ trợ là trình tự ưu tiên an toàn." },
    ],
    memory: "Biết nơi tập – có người giám sát – chân xuống trước – thở đều – dừng và bám khi bất ổn.",
  },
  "02": {
    safety: {
      title: "Lướt trong phạm vi kiểm soát",
      body: "Chỉ đẩy thành ở làn trống, vùng nước phù hợp và có người giám sát. Không đẩy mạnh về phía người khác; kết thúc pha lướt trước khi mất kiểm soát hô hấp hoặc tư thế.",
    },
    knowledge: [
      {
        title: "Tạo hình dạng thuôn dài",
        body: "Khi diện tích cản phía trước nhỏ hơn, cơ thể giữ vận tốc tốt hơn sau cú đẩy thành.",
        steps: ["Hai tay chồng nhẹ hoặc khép sát, duỗi thẳng ra trước.", "Cánh tay áp gần tai, vai thả lỏng.", "Hai chân khép, thân kéo dài theo hướng tiến."],
        cue: "Tay dài · đầu giữa tay · chân khép",
        avoid: "Không dang tay, gập khuỷu hoặc co gối ngay sau khi rời thành.",
      },
      {
        title: "Giữ đầu ở vị trí trung tính",
        body: "Đầu đi cùng đường thân; ngẩng quá cao làm hông và chân dễ hạ thấp, tăng lực cản.",
        steps: ["Mắt nhìn xuống và hơi chếch về trước.", "Gáy dài, không rụt cổ hoặc hất cằm.", "Kẹp đầu tự nhiên giữa hai cánh tay."],
        cue: "Mắt xuống · gáy dài · đầu yên",
        avoid: "Không cố nhìn thẳng về cuối bể trong lúc lướt sấp.",
      },
      {
        title: "Cân bằng đầu – hông – chân",
        body: "Lực nổi nâng cơ thể, còn sự thả lỏng và phân bố tư thế giúp hông, chân ở gần mặt nước hơn.",
        steps: ["Hít vừa đủ và giữ vai, cổ mềm.", "Ấn nhẹ ngực xuống thay vì ép đầu ngẩng lên.", "Giữ bụng có trương lực vừa phải, chân nối dài theo thân."],
        cue: "Ngực ổn · hông cao · chân dài",
        avoid: "Không gồng cứng toàn thân hoặc cố nâng đầu để tìm thăng bằng.",
      },
      {
        title: "Đẩy thành bằng hai chân",
        body: "Một cú đẩy cân đối tạo vận tốc ban đầu và giúp người học kiểm tra hình dạng cơ thể khi không quạt tay, đạp chân.",
        steps: ["Hai bàn chân đặt chắc trên thành, gần bề rộng hông.", "Hai tay tạo hình dài trước khi rời thành.", "Duỗi đồng thời hông, gối và cổ chân theo hướng tiến."],
        cue: "Tạo hình trước · hai chân đẩy cùng lúc",
        avoid: "Không quay người muộn, đẩy lệch một chân hoặc hướng thẳng vào người phía trước.",
      },
      {
        title: "Kết thúc lướt và đứng dậy",
        body: "Pha lướt kết thúc khi vận tốc giảm rõ hoặc người học cần lấy lại tư thế an toàn; không chờ đến lúc hoàn toàn mất kiểm soát.",
        steps: ["Thả khí đều khi đang lướt.", "Thu gối về dưới thân khi cần dừng.", "Đặt chân xuống đáy rồi mới nâng đầu và đứng thẳng."],
        cue: "Lướt · giảm tốc · thu gối · đứng",
        avoid: "Không vội quạt tay, đạp chân hoặc ngẩng đầu ngay sau cú đẩy.",
      },
    ],
    drills: [
      { code: "2.1", title: "Tạo hình trên bờ", goal: "Nhớ trục tay – đầu – thân", steps: ["Hai tay chồng nhẹ", "Cánh tay áp tai", "Chân khép và kéo dài"], volume: "2 lượt × 6 lần", pass: "Giữ đúng hình 5 giây", safety: "Không ưỡn lưng hoặc khóa cứng khớp" },
      { code: "2.2", title: "Nổi sấp rồi đứng dậy", goal: "Giữ cân bằng và kết thúc an toàn", steps: ["Nổi có hỗ trợ", "Mắt nhìn xuống", "Thu gối và đặt chân"], volume: "5 lần", pass: "Đúng trình tự 4/5 lần", safety: "Tập ở vùng nước nông" },
      { code: "2.3", title: "Đẩy nhẹ có hỗ trợ", goal: "Rời thành trong hình dạng thuôn dài", steps: ["Tạo hình trước", "Hai chân đẩy cùng lúc", "Không cử động trong hai nhịp"], volume: "6 lần × 2–3 m", pass: "Đi thẳng và thân không gãy", safety: "Người giám sát đứng phía trước, lệch khỏi đường lướt" },
      { code: "2.4", title: "Lướt qua mốc", goal: "Duy trì đầu, hông và chân gần một đường", steps: ["Chọn mốc 3 m", "Thở ra nhẹ", "Đứng dậy sau mốc"], volume: "6 lần", pass: "Qua mốc 4/6 lần mà không ngẩng đầu", safety: "Mốc nằm trong vùng đứng được" },
      { code: "2.5", title: "Lướt 5 m có kiểm soát", goal: "Đạt chuẩn cuối bài", steps: ["Kiểm tra làn trống", "Đẩy cân đối", "Giữ hình đến khi giảm tốc"], volume: "4–6 lần", pass: "Đạt 5 m ở 3 lần liên tiếp", safety: "Dừng ngay khi hụt hơi hoặc mất hướng" },
    ],
    mistakes: [
      { sign: "Đầu ngẩng, mắt nhìn thẳng", cause: "Muốn quan sát phía trước hoặc sợ úp mặt", fix: "Giảm cự ly; nhìn xuống mốc đáy và giữ gáy dài." },
      { sign: "Tay tách rộng hoặc khuỷu gập", cause: "Chưa tạo hình trước khi đẩy thành", fix: "Khóa trình tự: tay dài trước, chân mới đẩy." },
      { sign: "Hông và chân chìm nhanh", cause: "Đầu cao, thân gồng hoặc thở ra quá gấp", fix: "Thả cổ vai, mắt nhìn xuống và kéo dài chân theo trục thân." },
      { sign: "Rời thành bị lệch hướng", cause: "Hai bàn chân đặt lệch hoặc đẩy không đồng thời", fix: "Đặt hai chân cân đối và tập cú đẩy nhẹ trước khi tăng lực." },
    ],
    session: [
      { time: "08′", title: "Khởi động và an toàn", body: "Kiểm tra làn, làm ấm vai – hông – gối – cổ chân." },
      { time: "08′", title: "Tạo hình trên bờ", body: "Tay dài, đầu giữa tay, thân và chân nối thành một trục." },
      { time: "10′", title: "Nổi và đứng dậy", body: "Giữ đầu trung tính, cảm nhận cân bằng rồi kết thúc đúng trình tự." },
      { time: "12′", title: "Đẩy nhẹ 2–3 m", body: "Tạo hình trước khi rời thành; hai chân đẩy cùng lúc." },
      { time: "15′", title: "Lướt qua mốc", body: "Tăng dần đến 5 m khi tư thế vẫn thẳng và hô hấp được kiểm soát." },
      { time: "07′", title: "Đánh giá cuối bài", body: "Ba lần lướt 5 m, ghi một lỗi ưu tiên và hồi tĩnh." },
    ],
    questions: [
      { q: "Vị trí đầu phù hợp khi lướt sấp là gì?", options: ["Ngẩng cao để nhìn trước", "Đầu giữa hai tay, mắt nhìn xuống", "Quay hẳn sang một bên", "Cằm ép sát ngực"], answer: 1, explain: "Đầu trung tính giữa hai tay giúp duy trì đường thân dài và hạn chế hông, chân chìm." },
      { q: "Khi nào hai chân bắt đầu đẩy thành?", options: ["Trước khi hai tay duỗi", "Sau khi đã tạo hình thuôn dài", "Khi đầu đã ngẩng", "Sau một lần quạt tay"], answer: 1, explain: "Tạo hình cơ thể trước rồi mới đẩy giúp tận dụng vận tốc ban đầu và tránh thân bị gãy." },
      { q: "Dấu hiệu nào cho thấy pha lướt đang hiệu quả?", options: ["Tay dang rộng", "Gối co ngay", "Thân đi thẳng, đầu yên và giảm tốc từ từ", "Mặt luôn ở trên nước"], answer: 2, explain: "Một pha lướt tốt giữ trục cơ thể ổn định và không tạo cử động thừa ngay sau cú đẩy." },
      { q: "Cách kết thúc pha lướt an toàn là gì?", options: ["Ngẩng đầu trước", "Quạt tay thật mạnh", "Thu gối, đặt chân rồi nâng đầu", "Lăn sang làn bên"], answer: 2, explain: "Đặt chân tạo điểm tựa trước khi nâng đầu giúp người học đứng dậy có kiểm soát." },
      { q: "Hai cánh tay nên ở đâu trong tư thế lướt?", options: ["Dang ngang vai", "Duỗi về trước, áp gần tai", "Đặt dọc thân", "Một tay trước, một tay sau"], answer: 1, explain: "Hai tay duỗi về trước và áp gần tai giúp tạo hình dạng thuôn dài, giảm diện tích cản." },
      { q: "Vì sao ngẩng đầu cao làm pha lướt kém hiệu quả?", options: ["Làm chân đạp mạnh hơn", "Làm hông và chân dễ chìm, tăng lực cản", "Làm tay dài hơn", "Làm cơ thể nổi hoàn toàn"], answer: 1, explain: "Đầu lệch khỏi trục khiến phần dưới cơ thể hạ thấp và diện tích cản phía trước tăng." },
      { q: "Cú đẩy thành cân đối cần đặc điểm nào?", options: ["Một chân đẩy trước", "Hai chân đặt chắc và duỗi cùng lúc", "Đầu ngẩng trước khi rời thành", "Tay quạt ngay lập tức"], answer: 1, explain: "Hai chân đẩy đồng thời theo hướng tiến giúp cơ thể đi thẳng và giữ đúng hình lướt." },
      { q: "Khi đang lướt, cách thở phù hợp là gì?", options: ["Giữ hơi đến khi khó chịu", "Thở ra nhẹ và có kiểm soát", "Hít vào dưới nước", "Thở thật gấp ngay khi rời thành"], answer: 1, explain: "Thở ra nhẹ giúp duy trì bình tĩnh và chuẩn bị kết thúc pha lướt đúng lúc." },
      { q: "Nếu cơ thể lệch hướng ngay sau cú đẩy, nguyên nhân nên kiểm tra trước là gì?", options: ["Màu kính bơi", "Vị trí hai bàn chân và thời điểm đẩy", "Độ dài tóc", "Số lần thở"], answer: 1, explain: "Bàn chân đặt lệch hoặc hai chân đẩy không đồng thời là nguyên nhân trực tiếp thường gặp." },
      { q: "Khi vận tốc giảm rõ, người mới nên làm gì?", options: ["Cố giữ tư thế đến khi mất thăng bằng", "Thu gối, đặt chân và đứng dậy", "Quạt tay thật rộng", "Ngẩng đầu và đá liên tục"], answer: 1, explain: "Kết thúc trước khi mất kiểm soát giúp người học luôn chủ động và an toàn." },
    ],
    memory: "Tạo hình trước – đẩy hai chân cùng lúc – mắt nhìn xuống – thân kéo dài – thu gối rồi mới đứng.",
  },
  "04": {
    safety: {
      title: "Tập tay trong phạm vi kiểm soát",
      body: "Chỉ tập ở làn trống, độ sâu phù hợp và có người giám sát. Khi dùng phao hỗ trợ, phải kiểm tra phao ổn định trước khi rời thành. Dừng ngay nếu đau vai, hụt hơi, chóng mặt hoặc mất phương hướng.",
    },
    knowledge: [
      {
        title: "Tư thế bắt đầu và đường tay đối xứng",
        body: "Mỗi chu kỳ bắt đầu từ tư thế lướt: hai tay dài trước đầu, thân thuôn gọn và hai tay chuyển động đồng thời trên cùng một mặt phẳng ngang.",
        steps: ["Hai tay khép tự nhiên và duỗi về trước.", "Vai thả lỏng, đầu nằm giữa hai cánh tay.", "Bắt đầu tách hai bàn tay cùng lúc, không để một bên đi trước."],
        cue: "Tay dài · đầu giữa tay · hai bên cùng lúc",
        avoid: "Không gập khuỷu sớm, lệch một tay hoặc bắt đầu chu kỳ khi thân chưa ổn định.",
      },
      {
        title: "Tách tay và tỳ nước",
        body: "Hai bàn tay xoay nhẹ ra ngoài rồi tách chếch sang hai bên để tạo điểm tựa; biên độ vừa đủ giúp cảm nhận nước mà không làm tăng lực cản quá mức.",
        steps: ["Xoay lòng bàn tay hơi ra ngoài và chếch xuống.", "Tách tay chậm đến khi bàn tay, cẳng tay cảm nhận áp lực nước.", "Giữ khuỷu ở vị trí kiểm soát, không để bàn tay trượt vô lực."],
        cue: "Mở vừa · tỳ chắc · khuỷu kiểm soát",
        avoid: "Không quạt rộng quá vai hoặc ấn hai tay thẳng xuống đáy bể.",
      },
      {
        title: "Quạt vào và thu tay",
        body: "Sau khi tỳ nước, hai bàn tay quét vào trong; khuỷu gập có kiểm soát để đưa bàn tay về gần nhau trước ngực mà không kéo tay quá sâu về sau.",
        steps: ["Giữ áp lực nước khi cẳng tay chuyển hướng vào trong.", "Đưa khuỷu gần nhau dần nhưng không ép cứng.", "Thu hai bàn tay về trước ngực, chuẩn bị đưa tay ra trước."],
        cue: "Quạt vào · thu gọn · tay về trước ngực",
        avoid: "Không kéo bàn tay về sát bụng, để khuỷu tụt ra sau vai hoặc dừng quá lâu trước ngực.",
      },
      {
        title: "Đưa tay nhanh về trước",
        body: "Hai bàn tay đi thẳng về trước theo đường ngắn, khuỷu khép gọn rồi duỗi hoàn toàn để cơ thể sớm trở lại hình dạng ít lực cản.",
        steps: ["Ghép hai bàn tay gần nhau sau pha thu.", "Đưa tay về trước theo hướng bơi, không vòng xuống dưới.", "Duỗi khuỷu, xoay lòng bàn tay úp dần và khép thân để lướt."],
        cue: "Thu gọn · đưa thẳng · duỗi dài",
        avoid: "Không tách tay ngay khi chưa duỗi hết hoặc đưa tay vòng rộng sang hai bên.",
      },
      {
        title: "Hoàn tất một chu kỳ tay",
        body: "Nhịp tay hiệu quả có phần tạo lực gọn và phần đưa tay về trước dứt khoát; sau khi duỗi, giữ một khoảng ngắn để kiểm tra tư thế trước chu kỳ mới.",
        steps: ["Đếm chậm: mở – tỳ – quạt thu – duỗi.", "Giữ hai tay đồng thời trong toàn bộ chu kỳ.", "Chỉ bắt đầu chu kỳ mới khi tay đã dài và đầu trở lại vị trí ổn định."],
        cue: "Mở · tỳ · thu · dài",
        avoid: "Không quay tay liên tục không có điểm kết thúc hoặc cố tăng tốc khi đường tay còn sai.",
      },
    ],
    drills: [
      { code: "4.1", title: "Mô phỏng tay trên bờ", goal: "Nhớ đường tay và tính đồng thời", steps: ["Đứng hơi cúi thân", "Mở tay vừa phải", "Quạt thu rồi duỗi dài"], volume: "2 lượt × 8 chu kỳ", pass: "Đúng thứ tự 7/8 lần", safety: "Vai thả lỏng, không ép biên độ khi đau" },
      { code: "4.2", title: "Tỳ nước ở vùng nông", goal: "Cảm nhận áp lực ở bàn tay và cẳng tay", steps: ["Đứng vững", "Tách tay chậm", "Quạt vào và quan sát nước"], volume: "2 lượt × 10 lần", pass: "Cảm nhận được điểm tựa ở cả hai tay", safety: "Chỉ tập tại vị trí đứng chắc" },
      { code: "4.3", title: "Một chu kỳ tay – một lần lướt", goal: "Trở lại tư thế dài sau mỗi lần quạt", steps: ["Đẩy nhẹ khỏi thành", "Thực hiện một chu kỳ", "Duỗi tay và lướt đến mốc"], volume: "6 lần × 3–5 m", pass: "Tay duỗi hết trước khi bắt đầu lại", safety: "Làn trống, người giám sát trong tầm quan sát" },
      { code: "4.4", title: "Quạt tay có phao hỗ trợ chân", goal: "Giữ đường tay khi thân di chuyển", steps: ["Kẹp phao ổn định", "Quạt tay gọn", "Giữ đầu trung tính giữa các chu kỳ"], volume: "4 lượt × 10 m", pass: "Không kéo tay quá vai ở 3/4 lượt", safety: "Dừng nếu phao tuột hoặc mất kiểm soát thở" },
      { code: "4.5", title: "Tám chu kỳ tay có đếm nhịp", goal: "Duy trì kỹ thuật khi thực hiện liên tục", steps: ["Đếm bốn nhịp", "Hai tay cùng lúc", "Ghi một lỗi ưu tiên sau lượt"], volume: "3 lượt × 8 chu kỳ", pass: "Hoàn thành hai lượt đúng liên tiếp", safety: "Nghỉ đủ giữa lượt, không cố khi vai mỏi" },
    ],
    mistakes: [
      { sign: "Hai tay quạt quá rộng", cause: "Tìm lực bằng biên độ lớn thay vì tạo điểm tỳ sớm", fix: "Đặt mốc giới hạn gần trục vai; tập mở vừa rồi chuyển ngay sang quạt vào." },
      { sign: "Bàn tay kéo lùi quá vai", cause: "Pha tạo lực kéo dài và thu tay muộn", fix: "Thu khuỷu, đưa tay về trước ngay khi bàn tay ở gần trước ngực." },
      { sign: "Một tay đi trước tay còn lại", cause: "Cảm giác nước hai bên không đều hoặc mất tập trung", fix: "Mô phỏng chậm trước gương; dùng nhịp đếm để hai tay mở và khép cùng lúc." },
      { sign: "Duỗi tay chậm hoặc vòng rộng", cause: "Dừng lâu ở trước ngực và chưa chọn đường ngắn về trước", fix: "Tập riêng nhịp thu gọn – đưa thẳng – duỗi dài, sau đó mới ghép pha quạt." },
    ],
    session: [
      { time: "08′", title: "Khởi động và an toàn", body: "Làm ấm vai, khuỷu, cổ tay; kiểm tra làn, phao và tín hiệu dừng." },
      { time: "08′", title: "Mô phỏng trên bờ", body: "Ôn bốn giai đoạn, đường tay đối xứng và giới hạn quạt không quá rộng." },
      { time: "10′", title: "Cảm nhận tỳ nước", body: "Đứng vùng nông, tách tay chậm và giữ áp lực nước ở bàn tay, cẳng tay." },
      { time: "12′", title: "Một chu kỳ – một lần lướt", body: "Thực hiện đường tay trọn vẹn rồi trở lại tư thế thuôn dài." },
      { time: "15′", title: "Quạt tay có hỗ trợ", body: "Bốn lượt ngắn, ưu tiên tay không quá vai và đưa tay về trước gọn." },
      { time: "07′", title: "Đánh giá và hồi tĩnh", body: "Tám chu kỳ có đếm nhịp; chọn một lỗi ưu tiên cho buổi sau." },
    ],
    questions: [
      { q: "Điều kiện quan trọng nhất của hai tay trong bơi ếch là gì?", options: ["Hai tay chuyển động đồng thời", "Một tay quạt trước", "Tay thuận kéo mạnh hơn", "Hai tay luân phiên"], answer: 0, explain: "Hai tay phải chuyển động đồng thời để giữ đường bơi cân bằng và đúng đặc trưng kỹ thuật bơi ếch." },
      { q: "Vì sao không nên quạt tay quá rộng?", options: ["Làm chân đạp nhanh hơn", "Làm tăng đường đi và lực cản, khó thu tay", "Giúp đầu chìm sâu", "Không ảnh hưởng đến kỹ thuật"], answer: 1, explain: "Quạt quá rộng kéo dài đường tay, làm thu tay chậm và thường phá tư thế thuôn dài." },
      { q: "Sau khi hai bàn tay quạt vào trong, thao tác phù hợp là gì?", options: ["Kéo tay về sát bụng", "Dừng lâu trước ngực", "Thu gọn và đưa tay thẳng về trước", "Tách tay ngay sang hai bên"], answer: 2, explain: "Thu gọn rồi đưa tay theo đường ngắn về trước giúp cơ thể sớm trở lại tư thế ít lực cản." },
      { q: "Dấu hiệu nào cho thấy một chu kỳ tay đã kết thúc đúng?", options: ["Khuỷu còn gập", "Hai tay duỗi về trước, đầu ổn định", "Hai tay ở sau vai", "Bàn tay đang mở rộng"], answer: 1, explain: "Chu kỳ kết thúc khi hai tay đã duỗi dài về trước và cơ thể sẵn sàng bước vào pha lướt." },
      { q: "Từ tư thế lướt, hai bàn tay nên bắt đầu chu kỳ như thế nào?", options: ["Xoay nhẹ ra ngoài và tách đồng thời", "Ấn thẳng xuống đáy", "Kéo ngay về hông", "Một tay mở trước"], answer: 0, explain: "Xoay nhẹ bàn tay ra ngoài rồi tách đồng thời giúp tạo điểm tỳ mà vẫn giữ đường tay cân đối." },
      { q: "Bộ phận nào cùng bàn tay tạo mặt tỳ nước hiệu quả?", options: ["Chỉ các đầu ngón tay", "Bàn tay và cẳng tay", "Vai và gáy", "Khuỷu và bắp tay sau"], answer: 1, explain: "Cảm nhận áp lực trên cả bàn tay và cẳng tay giúp pha tỳ chắc hơn mà không cần quạt quá rộng." },
      { q: "Khi một tay luôn đi trước tay còn lại, cách sửa phù hợp nhất là gì?", options: ["Tăng tốc tay thuận", "Mở rộng cả hai tay", "Mô phỏng chậm trước gương và đếm nhịp đồng thời", "Kéo hai tay sâu hơn"], answer: 2, explain: "Mô phỏng chậm và dùng cùng một nhịp mở – thu cho hai bên giúp khôi phục tính đối xứng." },
      { q: "Đường đưa tay về trước nên có đặc điểm nào?", options: ["Vòng rộng sang hai bên", "Ngắn, gọn và hướng thẳng theo đường bơi", "Đi xuống sát bụng", "Dừng lâu trước ngực"], answer: 1, explain: "Đường về ngắn và thẳng giúp hai tay sớm trở lại tư thế thuôn dài, hạn chế mất vận tốc." },
      { q: "Nếu vai đau tăng dần khi tập quạt tay, người học nên làm gì?", options: ["Cố đủ số lượt", "Tăng biên độ để giãn vai", "Dừng bài gây đau và báo người giám sát", "Chỉ đổi sang tay thuận"], answer: 2, explain: "Đau tăng dần là tín hiệu phải dừng bài gây đau; không dùng sức hoặc biên độ lớn để cố vượt qua đau." },
      { q: "Khẩu lệnh nào mô tả đúng trọn một chu kỳ tay?", options: ["Mở – tỳ – quạt thu – duỗi", "Kéo – dừng – kéo – dừng", "Ấn xuống – kéo về hông – ngẩng", "Tách – đạp – nín – quay"], answer: 0, explain: "Mở – tỳ – quạt thu – duỗi giữ đúng thứ tự tạo điểm tựa, tạo lực, thu gọn và trở về tư thế dài." },
    ],
    memory: "Hai tay cùng lúc – mở vừa – tỳ chắc – quạt thu gọn – đưa thẳng và duỗi dài về trước.",
  },
  "05": {
    safety: {
      title: "Không thi nín thở và không thở dồn trước khi xuống nước",
      body: "Chỉ luyện thở trong phạm vi có người giám sát, gần điểm bám hoặc ở cự ly phù hợp năng lực. Không cố kéo dài thời gian úp mặt, không thở nhanh dồn dập trước khi lặn và dừng ngay khi chóng mặt, tức ngực hoặc khó thở.",
    },
    knowledge: [
      {
        title: "Tạo vòng hô hấp chủ động",
        body: "Nhịp thở bơi ếch gồm một lần hít vào nhanh khi miệng ở trên nước và một lần thở ra có kiểm soát khi mặt trở lại dưới nước.",
        steps: ["Hít vào vừa đủ bằng miệng, không cố lấy quá đầy.", "Đưa mặt trở lại nước và bắt đầu thở ra có kiểm soát.", "Kết thúc thở ra trước lần hít tiếp theo để không bị dồn nhịp."],
        cue: "Hít nhanh · thở kiểm soát · không giữ hơi",
        avoid: "Không nín thở kéo dài, thở dồn hoặc cố tập tiếp khi đã hụt hơi.",
      },
      {
        title: "Hít vào theo pha quạt – thu tay",
        body: "Khi tay tỳ và quạt vào, vai nâng thân trên vừa đủ để miệng ra khỏi nước; đây là thời điểm hít vào mà không cần hất đầu lên cao.",
        steps: ["Bắt đầu nâng vai tự nhiên khi tay chuyển sang quạt vào.", "Giữ mắt nhìn chếch xuống trước, cằm gần mặt nước.", "Hít nhanh bằng miệng trước khi tay duỗi về trước."],
        cue: "Tay quạt · vai nâng · miệng hít",
        avoid: "Không chờ đến khi tay đã duỗi mới ngẩng đầu lấy hơi.",
      },
      {
        title: "Đầu đi theo vai, không hất cằm",
        body: "Vai dẫn thân trên lên đủ để thở; đầu giữ gần vị trí trung tính giúp hông, chân không chìm sâu và giảm lực cản phía trước.",
        steps: ["Giữ gáy dài khi thân trên nâng lên.", "Chỉ đưa miệng qua mặt nước, không cố nâng toàn bộ đầu cao.", "Sau khi hít, để đầu trở lại giữa hai tay khi tay duỗi."],
        cue: "Vai dẫn · cằm thấp · đầu về giữa tay",
        avoid: "Không hất cằm, nhìn thẳng cao hoặc giữ đầu trên nước suốt chu kỳ.",
      },
      {
        title: "Thở ra khi tay duỗi và cơ thể lướt",
        body: "Sau khi hít, mặt trở lại nước cùng lúc hai tay đưa về trước; thở ra trong phần duỗi – lướt giúp chuẩn bị cho lần hít kế tiếp.",
        steps: ["Đưa đầu xuống khi hai tay bắt đầu duỗi.", "Thở ra bằng mũi hoặc phối hợp mũi và miệng.", "Duy trì dòng khí phù hợp đến gần cuối pha lướt."],
        cue: "Tay dài · mặt xuống · thở ra",
        avoid: "Không giữ toàn bộ hơi đến sát lần hít tiếp theo rồi mới thở gấp.",
      },
      {
        title: "Giữ nhịp một chu kỳ – một lần thở",
        body: "Ở giai đoạn học cơ bản, mỗi chu kỳ tay đi với một lần hít vào; nhịp đều quan trọng hơn tốc độ hoặc số mét bơi được.",
        steps: ["Đếm: quạt – hít – duỗi – thở ra.", "Giữ cùng một thời điểm hít trong nhiều chu kỳ liên tiếp.", "Khi mất nhịp, dừng ở điểm an toàn rồi quay về bài tập ngắn hơn."],
        cue: "Một chu kỳ · một lần hít · nhịp đều",
        avoid: "Không bỏ nhịp thở tùy ý hoặc tăng tốc tay để bù khi hụt hơi.",
      },
    ],
    drills: [
      { code: "5.1", title: "Hít – thở tại thành bể", goal: "Tạo vòng hô hấp bình tĩnh", steps: ["Hai tay bám thành", "Hít bằng miệng", "Úp mặt và thở ra"], volume: "2 lượt × 8 lần", pass: "Tám vòng liên tục không nín giữ", safety: "Dừng nếu chóng mặt hoặc ho sặc" },
      { code: "5.2", title: "Tay – thở khi đứng vùng nông", goal: "Ghép thời điểm hít với pha quạt", steps: ["Quạt tay và nâng vai", "Hít nhanh", "Duỗi tay, mặt xuống và thở ra"], volume: "2 lượt × 8 chu kỳ", pass: "Đúng thời điểm 7/8 lần", safety: "Hai chân đứng chắc, không di chuyển ra vùng sâu" },
      { code: "5.3", title: "Một chu kỳ tay – một lần thở", goal: "Giữ đầu trở lại giữa hai tay", steps: ["Đẩy nhẹ", "Quạt và hít", "Duỗi, thở ra rồi đứng dậy"], volume: "6 lần × 3–5 m", pass: "Không hất cằm ở 5/6 lần", safety: "Thực hiện gần thành và trong vùng kiểm soát" },
      { code: "5.4", title: "Tay – thở có phao hỗ trợ", goal: "Duy trì nhịp khi cơ thể di chuyển", steps: ["Kiểm tra phao", "Một chu kỳ một lần hít", "Thở ra khi duỗi – lướt"], volume: "4 lượt × 10 m", pass: "Ba lượt có nhịp ổn định", safety: "Dừng nếu phao tuột hoặc nhịp thở rối" },
      { code: "5.5", title: "Tám chu kỳ tay – thở liên tục", goal: "Đạt chuẩn cuối bài", steps: ["Đếm bốn nhịp", "Giữ cằm thấp", "Kết thúc ở điểm bám an toàn"], volume: "3 lượt × 8 chu kỳ", pass: "Hai lượt liên tiếp không hụt hơi", safety: "Nghỉ đầy đủ giữa lượt, không cố vượt giới hạn" },
    ],
    mistakes: [
      { sign: "Ngẩng đầu cao để lấy hơi", cause: "Cố đưa mặt lên bằng cổ thay vì để vai dẫn chuyển động", fix: "Giảm cự ly; tập vai nâng nhẹ, cằm gần nước và đầu trở lại giữa hai tay." },
      { sign: "Giữ đầu trên mặt nước quá lâu", cause: "Lo không đủ thời gian hít hoặc tay duỗi chậm", fix: "Hít nhanh khi tay quạt vào; đưa đầu xuống cùng lúc tay đi về trước." },
      { sign: "Nín thở đến cuối pha lướt", cause: "Chưa tạo thói quen thở ra khi mặt dưới nước", fix: "Quay lại bài thổi khí tại thành; bắt đầu thở ra ngay sau khi mặt trở lại nước." },
      { sign: "Nhịp hít lúc sớm lúc muộn", cause: "Chưa gắn hô hấp với một mốc cố định của động tác tay", fix: "Dùng nhịp đếm quạt – hít – duỗi – thở ra trong các đoạn ngắn." },
    ],
    session: [
      { time: "08′", title: "Khởi động và nhắc an toàn", body: "Làm ấm vai, cổ; nhắc không nín thở kéo dài hoặc thở dồn trước khi xuống nước." },
      { time: "08′", title: "Hô hấp tại thành bể", body: "Hai lượt hít bằng miệng, úp mặt và thở ra có kiểm soát." },
      { time: "10′", title: "Tay – thở khi đứng", body: "Ghép pha quạt với nâng vai, hít nhanh và đưa đầu về khi tay duỗi." },
      { time: "12′", title: "Một chu kỳ – một lần thở", body: "Sáu đoạn ngắn, ưu tiên cằm thấp và đầu trở lại giữa hai tay." },
      { time: "15′", title: "Duy trì nhịp khi di chuyển", body: "Bốn lượt có hỗ trợ; thở ra trong phần duỗi – lướt và nghỉ đủ giữa lượt." },
      { time: "07′", title: "Đánh giá và hồi tĩnh", body: "Tám chu kỳ liên tục; ghi lại một lỗi thở cần ưu tiên ở buổi sau." },
    ],
    questions: [
      { q: "Thời điểm phù hợp để hít vào trong bơi ếch là khi nào?", options: ["Khi tay tỳ – quạt và vai nâng miệng khỏi nước", "Giữa pha lướt", "Sau khi chân đã dừng", "Bất kỳ lúc nào thấy thiếu hơi"], answer: 0, explain: "Pha quạt – thu tay nâng thân trên vừa đủ để miệng ra khỏi nước và hít vào mà không cần hất đầu." },
      { q: "Cách đưa đầu lên lấy hơi phù hợp là gì?", options: ["Hất cằm thật cao", "Để vai dẫn, giữ cằm gần mặt nước", "Giữ đầu trên nước suốt chu kỳ", "Quay đầu sang một bên"], answer: 1, explain: "Vai dẫn chuyển động và cằm thấp giúp hạn chế hông, chân chìm và giảm lực cản." },
      { q: "Khi nào nên thở ra?", options: ["Chỉ thở ra ngay trước lần hít kế tiếp", "Khi mặt dưới nước trong phần tay duỗi – lướt", "Khi miệng vừa khỏi nước", "Sau khi đã đứng dậy"], answer: 1, explain: "Thở ra có kiểm soát khi mặt dưới nước giúp vòng hô hấp không bị dồn vào cuối chu kỳ." },
      { q: "Nhịp cơ bản phù hợp cho người đang học là gì?", options: ["Ba chu kỳ mới hít một lần", "Một chu kỳ tay – một lần hít", "Nín thở càng lâu càng tốt", "Hít hai lần trong một chu kỳ"], answer: 1, explain: "Một chu kỳ tay đi với một lần hít tạo nhịp đều, dễ kiểm soát và phù hợp giai đoạn học cơ bản." },
      { q: "Sau khi hít vào, đầu nên trở lại nước vào thời điểm nào?", options: ["Khi hai tay bắt đầu duỗi về trước", "Sau khi cơ thể đã dừng", "Trước khi tay quạt vào", "Chỉ khi đã hết hơi"], answer: 0, explain: "Đưa đầu trở lại giữa hai tay khi tay duỗi giúp khôi phục đường thân và bắt đầu pha thở ra – lướt." },
      { q: "Vì sao hất cằm lên cao thường làm nhịp bơi kém hiệu quả?", options: ["Làm tay dài hơn", "Làm hông và chân dễ chìm, tăng lực cản", "Làm thở ra quá sớm", "Làm phao nổi hơn"], answer: 1, explain: "Nâng đầu bằng cổ thay vì để vai dẫn thường kéo phần dưới cơ thể xuống và làm tăng diện tích cản." },
      { q: "Dấu hiệu nào cho thấy người học đang giữ hơi quá lâu?", options: ["Dòng bọt khí đều", "Phải thở gấp ngay trước lần hít kế tiếp", "Cằm luôn gần mặt nước", "Nhịp tay ổn định"], answer: 1, explain: "Nếu chỉ thở dồn ở cuối chu kỳ, vòng hô hấp dễ rối và lần hít tiếp theo trở nên vội vàng." },
      { q: "Khi hụt hơi và mất nhịp trong đoạn tập, lựa chọn an toàn là gì?", options: ["Tăng tốc tay để về đích", "Nín thở thêm một chu kỳ", "Dừng ở điểm bám gần nhất và quay về bài tập ngắn hơn", "Ngẩng đầu liên tục nhưng vẫn bơi"], answer: 2, explain: "Dừng ở điểm bám, ổn định hô hấp rồi giảm độ khó giúp khôi phục kiểm soát thay vì cố hoàn thành quãng đường." },
      { q: "Tiêu chí phù hợp cho bài tám chu kỳ tay – thở là gì?", options: ["Hai lượt liên tiếp giữ một chu kỳ – một lần hít mà không hụt hơi", "Một lượt thật nhanh", "Nín thở được bốn chu kỳ", "Luôn giữ đầu trên mặt nước"], answer: 0, explain: "Chuẩn thực hành ưu tiên nhịp thở ổn định và lặp lại được, không lấy tốc độ hoặc thời gian nín thở làm mục tiêu." },
      { q: "Khẩu lệnh nào ghép đúng tay với hô hấp?", options: ["Quạt – hít; duỗi – đầu xuống – thở ra", "Duỗi – hít; quạt – nín", "Lướt – hít; kéo – giữ hơi", "Đạp – hít; dừng – thở"], answer: 0, explain: "Hít diễn ra khi tay quạt và vai nâng; khi tay duỗi, đầu trở lại giữa tay và thở ra có kiểm soát." },
    ],
    memory: "Tay quạt – vai nâng – hít nhanh; tay duỗi – đầu về giữa tay – thở ra có kiểm soát.",
  },
  "06": {
    safety: {
      title: "Giữ chất lượng nhịp trước khi tăng quãng đường",
      body: "Chỉ ghép toàn bộ động tác tại làn trống, độ sâu phù hợp và có người giám sát. Dừng ở điểm bám gần nhất nếu hụt hơi, mất hướng, chuột rút hoặc nhịp tay – chân rối; không cố hoàn thành đủ 25 m bằng động tác mất kiểm soát.",
    },
    knowledge: [
      {
        title: "Bắt đầu từ tư thế lướt",
        body: "Một chu kỳ hiệu quả bắt đầu và kết thúc ở hình dạng thuôn dài: tay duỗi trước, đầu giữa tay, chân khép và thân ổn định.",
        steps: ["Hai tay dài và gần nhau ở phía trước.", "Mắt nhìn xuống, gáy dài, hông gần mặt nước.", "Chân khép, bàn chân duỗi và chưa thu khi tay bắt đầu tỳ."],
        cue: "Tay dài · đầu yên · chân khép",
        avoid: "Không bắt đầu quạt tay khi cơ thể còn lệch hoặc co gối sớm trong pha lướt.",
      },
      {
        title: "Quạt tay và hít vào",
        body: "Tay tỳ – quạt tạo lực và nâng vai vừa đủ để miệng ra khỏi nước; trong giai đoạn này hai chân vẫn giữ dài để tránh tạo lực cản cùng lúc.",
        steps: ["Tách tay vừa phải và giữ áp lực nước.", "Quạt vào, để vai dẫn miệng lên lấy hơi.", "Hít nhanh bằng miệng khi hai bàn tay thu gần trước ngực."],
        cue: "Quạt – nâng vai – hít",
        avoid: "Không thu gối mạnh ngay khi tay vừa mở hoặc hất cằm lên để lấy hơi.",
      },
      {
        title: "Đưa tay về trước và thu chân",
        body: "Khi hai tay rời pha tạo lực và đi nhanh về trước, gót bắt đầu thu về. Tay phải sớm tạo lại đường thân để chuẩn bị nhận lực từ cú đạp.",
        steps: ["Khép khuỷu và đưa hai bàn tay thẳng về trước.", "Đầu trở lại giữa hai tay, bắt đầu thở ra.", "Thu gót gọn, gối mở vừa và bẻ bàn chân trước khi đạp."],
        cue: "Tay về trước · đầu xuống · gót thu gọn",
        avoid: "Không dừng tay trước ngực hoặc kéo hai gối sâu về bụng.",
      },
      {
        title: "Duỗi tay, đạp – khép chân",
        body: "Cú đạp bắt đầu khi hai tay đã gần duỗi hết về trước; nước được đẩy ra sau, chân quét vào và khép để đưa toàn thân trở lại tư thế dài.",
        steps: ["Giữ hai tay dài và cố định theo hướng tiến.", "Đạp nước ra sau bằng hai chân đồng thời.", "Quét vào trong, khép chân và duỗi bàn chân ở cuối pha."],
        cue: "Tay dài trước · chân đạp sau · khép kín",
        avoid: "Không để tay và chân cùng quạt mạnh theo hai hướng làm thân bị gãy.",
      },
      {
        title: "Lướt và chọn thời điểm bắt đầu chu kỳ mới",
        body: "Sau khi chân khép, giữ thân thuôn dài trong một khoảng phù hợp để tận dụng vận tốc; bắt đầu chu kỳ mới trước khi cơ thể giảm tốc quá nhiều.",
        steps: ["Giữ tay, đầu, thân và chân trên một đường dài.", "Thở ra có kiểm soát trong phần lướt.", "Khi vận tốc giảm rõ, bắt đầu tỳ tay cho chu kỳ kế tiếp."],
        cue: "Khép – dài – lướt – rồi mới quạt",
        avoid: "Không bỏ hẳn pha lướt hoặc chờ đến khi gần dừng mới bắt đầu chu kỳ mới.",
      },
    ],
    drills: [
      { code: "6.1", title: "Ghép nhịp trên cạn", goal: "Nhớ đúng thứ tự của một chu kỳ", steps: ["Quạt tay và hít", "Đưa tay về trước, thu gót", "Đạp – khép rồi giữ tư thế dài"], volume: "2 lượt × 8 chu kỳ", pass: "Đúng thứ tự 7/8 lần", safety: "Tập chậm, không ép biên độ gối hoặc vai" },
      { code: "6.2", title: "Một tay – một chân có đếm nhịp", goal: "Tách rõ thời điểm tạo lực của tay và chân", steps: ["Đếm quạt – thở", "Đếm tay dài – chân đạp", "Giữ một nhịp lướt"], volume: "6 lần × 5 m", pass: "Không co gối khi tay vừa mở ở 5/6 lần", safety: "Thực hiện gần thành, nghỉ khi hụt hơi" },
      { code: "6.3", title: "Một chu kỳ – một lần lướt", goal: "Tạo điểm kết thúc rõ cho từng chu kỳ", steps: ["Đẩy nhẹ từ thành", "Thực hiện một chu kỳ hoàn chỉnh", "Lướt đến mốc rồi đứng dậy"], volume: "6–8 lần × 5–8 m", pass: "Giữ thân dài sau cú đạp ở 6 lần", safety: "Mốc nằm trong khu vực kiểm soát" },
      { code: "6.4", title: "Ba chu kỳ liên tục", goal: "Duy trì nhịp mà không rút ngắn pha lướt", steps: ["Đếm quạt – thở – đạp – lướt", "Giữ cùng một nhịp ở ba chu kỳ", "Dừng và tự nêu một lỗi"], volume: "4 lượt × 3 chu kỳ", pass: "Ba lượt không chồng lực tay – chân", safety: "Có điểm bám ở cuối mỗi lượt" },
      { code: "6.5", title: "Bơi 25 m có kiểm soát", goal: "Đạt chuẩn phối hợp cuối bài", steps: ["Kiểm tra làn trống", "Giữ một nhịp ổn định", "Ghi số chu kỳ và lỗi ưu tiên"], volume: "3–4 lượt × 25 m", pass: "Hai lượt đúng trình tự và có pha lướt rõ", safety: "Dừng sớm nếu chất lượng nhịp hoặc hô hấp giảm" },
    ],
    mistakes: [
      { sign: "Tay và chân cùng tạo lực", cause: "Người học cố làm nhanh nên thu, quạt và đạp gần như đồng thời", fix: "Quay về nhịp đếm: quạt – thở; tay dài – chân đạp; khép – lướt." },
      { sign: "Thu gối ngay khi tay vừa mở", cause: "Chưa giữ chân dài trong pha tạo lực của tay", fix: "Tập ba chu kỳ chỉ chú ý tín hiệu chân dài đến khi hai tay bắt đầu thu vào." },
      { sign: "Đạp chân khi tay còn trước ngực", cause: "Pha đưa tay về trước quá chậm hoặc cú đạp bắt đầu quá sớm", fix: "Ưu tiên đưa tay thẳng và gần duỗi hết rồi mới bắt đầu đạp." },
      { sign: "Không lướt hoặc lướt đến gần dừng", cause: "Chưa cảm nhận thời điểm chuyển giữa giữ vận tốc và bắt đầu chu kỳ mới", fix: "Dùng mốc đếm ngắn; bắt đầu quạt khi vận tốc vừa giảm rõ, không sớm hoặc quá muộn." },
    ],
    session: [
      { time: "08′", title: "Khởi động và kiểm tra an toàn", body: "Làm ấm vai, hông, gối, cổ chân; thống nhất làn bơi và tín hiệu dừng." },
      { time: "10′", title: "Ghép nhịp trên cạn", body: "Mô phỏng chậm theo thứ tự quạt – thở – tay về – đạp – lướt." },
      { time: "12′", title: "Đoạn ngắn có đếm nhịp", body: "Một chu kỳ rồi ba chu kỳ; tách rõ thời điểm tạo lực của tay và chân." },
      { time: "15′", title: "Duy trì phối hợp", body: "Các lượt 10–15 m, giữ đầu về giữa tay và một khoảng lướt ổn định." },
      { time: "10′", title: "Đánh giá 25 m", body: "Hai đến ba lượt có ghi số chu kỳ, nhịp thở và một lỗi ưu tiên." },
      { time: "05′", title: "Hồi tĩnh", body: "Thả lỏng, ổn định hô hấp và chọn nội dung cần sửa ở Bài 07." },
    ],
    questions: [
      { q: "Trình tự ghi nhớ phù hợp cho một chu kỳ bơi ếch là gì?", options: ["Quạt – thở – đạp – lướt", "Đạp – quạt – nín thở – dừng", "Quạt và đạp đồng thời – lướt", "Lướt – đạp – quạt – thở"], answer: 0, explain: "Trình tự quạt – thở – đạp – lướt giúp tách rõ giai đoạn tạo lực của tay, chân và phần giữ vận tốc." },
      { q: "Khi tay bắt đầu tỳ và quạt nước, hai chân nên ở trạng thái nào?", options: ["Thu gối sâu", "Đạp thật mạnh", "Duỗi dài và khép", "Mở rộng sang hai bên"], answer: 2, explain: "Giữ chân duỗi trong pha tạo lực của tay giúp hạn chế lực cản và tránh chồng hai động tác." },
      { q: "Cú đạp nên bắt đầu vào thời điểm nào?", options: ["Khi tay vừa mở", "Khi tay đã gần duỗi hết về trước", "Khi đầu còn ngẩng cao", "Sau khi cơ thể dừng hẳn"], answer: 1, explain: "Tay gần duỗi hết tạo đường thân ổn định để nhận lực tiến từ cú đạp chân." },
      { q: "Dấu hiệu nào cho thấy nhịp phối hợp cần dừng và quay về đoạn ngắn?", options: ["Có pha lướt rõ", "Hô hấp đều", "Tay – chân chồng lực và thân mất kiểm soát", "Số chu kỳ giảm"], answer: 2, explain: "Khi động tác rối và hô hấp hoặc tư thế mất kiểm soát, cần giảm quãng đường để khôi phục đúng trình tự." },
      { q: "Nên bắt đầu chu kỳ mới vào thời điểm nào trong pha lướt?", options: ["Ngay khi chân vừa khép", "Khi vận tốc bắt đầu giảm rõ nhưng cơ thể chưa gần dừng", "Chỉ khi cơ thể đã dừng hẳn", "Sau một khoảng đếm cố định ở mọi tốc độ"], answer: 1, explain: "Pha lướt cần đủ để tận dụng vận tốc, nhưng không kéo dài đến gần dừng; dấu hiệu phù hợp là lúc vận tốc vừa giảm rõ." },
      { q: "Co gối ngay khi hai tay vừa mở thường gây hậu quả gì?", options: ["Giảm lực cản phía trước", "Làm chân tạo lực mạnh hơn", "Tăng lực cản và chồng thời điểm phục hồi tay – chân", "Giúp pha lướt dài hơn"], answer: 2, explain: "Thu chân quá sớm làm hình dạng cơ thể kém thuôn và khiến tay – chân cùng phục hồi, gây lực cản lớn." },
      { q: "Khẩu lệnh nào tách thời điểm tạo lực của tay và chân rõ nhất?", options: ["Tay và chân cùng mạnh", "Quạt – thở; tay dài – chân đạp; khép – lướt", "Đạp – giữ hơi; quạt – dừng", "Quạt liên tục, bỏ lướt"], answer: 1, explain: "Khẩu lệnh này đặt lực tay trước, đưa tay về đường thân rồi mới dùng lực chân và kết thúc bằng pha lướt." },
      { q: "Tiêu chí thực hành phù hợp nhất cho bài bơi 25 m là gì?", options: ["Một lượt nhanh nhất", "Hai lượt giữ đúng trình tự và có pha lướt rõ", "Số chu kỳ càng nhiều càng tốt", "Không cần nghỉ giữa các lượt"], answer: 1, explain: "Chuẩn cuối bài ưu tiên khả năng lặp lại đúng trình tự và giữ pha lướt, không lấy một lượt tốc độ cao làm bằng chứng duy nhất." },
      { q: "Vì sao hai tay cần gần duỗi hết trước khi chân đạp?", options: ["Để cơ thể có đường thân gọn nhận lực từ cú đạp", "Để đầu luôn ở trên mặt nước", "Để hai gối mở rộng hơn", "Để dừng thở ra"], answer: 0, explain: "Khi tay đã dài về trước, cơ thể trở lại hình dạng thuôn để lực từ cú đạp đẩy toàn thân tiến lên hiệu quả hơn." },
      { q: "Nếu hụt hơi ở cuối đoạn phối hợp, cách xử lý đúng là gì?", options: ["Tăng tần số tay để cố về đích", "Ngẩng đầu liên tục và tiếp tục bơi", "Dừng ở điểm bám gần nhất, ổn định thở rồi giảm quãng tập", "Nín thở thêm một chu kỳ"], answer: 2, explain: "An toàn và kiểm soát hô hấp được ưu tiên; sau khi ổn định, quay về đoạn ngắn giúp khôi phục nhịp đúng." },
    ],
    memory: "Quạt – thở; tay về trước – gót thu; tay dài – chân đạp; khép kín – thân lướt.",
  },
  "07": {
    safety: {
      title: "Sửa lỗi trong điều kiện an toàn và có thể quan sát",
      body: "Chỉ ghi hình khi người bơi đã đồng ý, thiết bị được giữ ngoài vùng gây vướng và có người phụ trách quan sát an toàn. Ưu tiên lỗi gây đau, hụt hơi hoặc mất kiểm soát; dừng ngay bài tập gây đau thay vì cố lặp lại để lấy đủ số lần.",
    },
    knowledge: [
      {
        title: "Mô tả biểu hiện có thể nhìn thấy",
        body: "Một nhận xét hữu ích phải chỉ ra hành vi cụ thể thay vì nói chung rằng động tác xấu, yếu hoặc chưa đúng.",
        steps: ["Quan sát từ bên để xem đầu, hông, đường tay và thời điểm thở.", "Quan sát từ phía sau để xem đối xứng của tay, gối và bàn chân.", "Ghi lại đúng một biểu hiện ở mỗi lượt bơi."],
        cue: "Nhìn thấy gì · ghi đúng điều đó",
        avoid: "Không kết luận nguyên nhân khi mới chỉ quan sát một góc hoặc một chu kỳ.",
      },
      {
        title: "Xếp thứ tự lỗi cần sửa",
        body: "Không phải lỗi nào cũng có mức ưu tiên như nhau. Lỗi an toàn và dấu hiệu đau phải xử lý trước, sau đó mới đến lực cản, phối hợp và hiệu quả.",
        steps: ["Chặn lỗi gây đau, hụt hơi hoặc mất phương hướng.", "Chọn lỗi phá tư thế hoặc phá trình tự tay – chân.", "Chỉ chọn một lỗi ưu tiên cho lượt sửa kế tiếp."],
        cue: "An toàn trước · nhịp sau · tốc độ cuối",
        avoid: "Không sửa đồng thời đầu, tay, gối và bàn chân trong cùng một lượt.",
      },
      {
        title: "Kiểm tra một nguyên nhân chính",
        body: "Cùng một biểu hiện có thể đến từ nhiều nguyên nhân. Bài tập sửa phải giúp kiểm tra một giả thuyết rõ ràng, không chỉ tạo thêm khối lượng.",
        steps: ["Nêu biểu hiện và một nguyên nhân có khả năng nhất.", "Chọn một tín hiệu ngắn để thay đổi nguyên nhân đó.", "Thực hiện ba lượt rồi quan sát xem biểu hiện có giảm không."],
        cue: "Một lỗi · một nguyên nhân · một tín hiệu",
        avoid: "Không đổi bài tập sau từng lần thử hoặc giải thích quá nhiều khi người học đang bơi.",
      },
      {
        title: "Sửa theo bậc từ đơn giản đến hoàn chỉnh",
        body: "Hạ độ khó giúp người học cảm nhận đúng trước khi đưa động tác trở lại toàn bộ chu kỳ.",
        steps: ["Mô phỏng chậm trên cạn để hiểu hình dạng.", "Tập có điểm tựa hoặc dụng cụ trong đoạn ngắn.", "Ghép vào ba chu kỳ hoàn chỉnh rồi bơi lại quãng đánh giá."],
        cue: "Trên cạn · có điểm tựa · đoạn ngắn · ghép lại",
        avoid: "Không lặp cả 25 m bằng động tác sai rồi mới nhận xét ở cuối lượt.",
      },
      {
        title: "Đánh giá lại bằng cùng một tiêu chí",
        body: "So sánh trước – sau chỉ có ý nghĩa khi góc quan sát, quãng đường và tiêu chí chính được giữ tương đối giống nhau.",
        steps: ["Lặp lại đúng quãng đường hoặc số chu kỳ ban đầu.", "Quan sát lại cùng dấu hiệu đã chọn.", "Ghi mức cải thiện và quyết định giữ, đổi hoặc bỏ tín hiệu sửa."],
        cue: "Cùng tiêu chí · cùng quãng · so trước sau",
        avoid: "Không dùng tốc độ làm thước đo duy nhất khi mục tiêu là sửa kỹ thuật.",
      },
    ],
    drills: [
      { code: "7.1", title: "Phiếu quan sát hai góc", goal: "Gọi tên biểu hiện cụ thể", steps: ["Quan sát một lượt từ bên", "Quan sát một lượt từ sau", "Ghi tối đa hai dấu hiệu"], volume: "2 lượt × 10–15 m", pass: "Mỗi nhận xét mô tả được hành vi nhìn thấy", safety: "Người quan sát đứng ngoài đường bơi" },
      { code: "7.2", title: "Chọn một lỗi ưu tiên", goal: "Tập trung đúng nội dung cần sửa trước", steps: ["Loại trừ dấu hiệu đau hoặc mất an toàn", "Đánh dấu lỗi phá nhịp lớn nhất", "Chọn một tín hiệu ngắn"], volume: "1 phiếu mỗi buổi", pass: "Chỉ có một lỗi và một tín hiệu sửa", safety: "Nếu có đau, dừng bài gây đau và nhờ kiểm tra" },
      { code: "7.3", title: "Ba bậc sửa lỗi", goal: "Hình thành lại động tác trong điều kiện dễ kiểm soát", steps: ["Ba lần trên cạn", "Ba lần có điểm tựa", "Ba đoạn ngắn trong nước"], volume: "3 lượt ở mỗi bậc", pass: "Dấu hiệu sai giảm ở ít nhất hai bậc", safety: "Không tăng biên độ khi khớp khó chịu" },
      { code: "7.4", title: "Ba chu kỳ có một tín hiệu", goal: "Đưa cách sửa trở lại động tác hoàn chỉnh", steps: ["Nhắc tín hiệu trước khi bơi", "Thực hiện ba chu kỳ", "Nhận phản hồi bằng một câu"], volume: "4–6 lượt × 3 chu kỳ", pass: "Duy trì tín hiệu đúng ở ba lượt", safety: "Có điểm bám gần cuối mỗi lượt" },
      { code: "7.5", title: "So sánh trước – sau", goal: "Xác nhận cách sửa thực sự có hiệu quả", steps: ["Bơi lại cùng quãng đánh giá", "Ghi cùng tiêu chí", "Chọn giữ hoặc đổi bài tập"], volume: "2 lượt trước + 2 lượt sau", pass: "Ít nhất một dấu hiệu cải thiện rõ", safety: "Nghỉ đủ để mệt không làm sai kết quả" },
    ],
    mistakes: [
      { sign: "Chỉ nhận xét “bơi chưa đúng”", cause: "Quan sát không có tiêu chí hoặc cố theo dõi quá nhiều chi tiết", fix: "Chọn một góc quan sát và mô tả một hành vi cụ thể như gối mở rộng hoặc đầu ngẩng cao." },
      { sign: "Đưa nhiều khẩu lệnh trong một lượt", cause: "Muốn sửa nhanh tất cả lỗi cùng lúc", fix: "Giữ một khẩu lệnh ngắn trong ba lượt rồi mới đánh giá có chuyển sang lỗi khác hay không." },
      { sign: "Tăng quãng đường khi kỹ thuật đang hỏng", cause: "Dùng số mét thay cho chất lượng động tác", fix: "Giảm về ba chu kỳ hoặc 5–10 m; chỉ tăng khi tín hiệu đúng lặp lại ổn định." },
      { sign: "Đổi bài tập nhưng không kiểm tra lại", cause: "Không khóa tiêu chí trước – sau", fix: "Lặp lại cùng góc, cùng quãng và cùng dấu hiệu để quyết định bài tập có hiệu quả." },
    ],
    session: [
      { time: "08′", title: "Khởi động và khóa tiêu chí", body: "Làm ấm toàn thân, chọn một nội dung kỹ thuật và thống nhất cách quan sát." },
      { time: "10′", title: "Ghi lượt ban đầu", body: "Hai lượt ngắn từ góc bên và phía sau; mô tả tối đa hai biểu hiện." },
      { time: "10′", title: "Chọn lỗi ưu tiên", body: "Xử lý an toàn trước, xác định một nguyên nhân và một tín hiệu sửa ngắn." },
      { time: "15′", title: "Sửa theo ba bậc", body: "Trên cạn, có điểm tựa rồi đoạn ngắn; mỗi bậc ba lượt có quan sát." },
      { time: "12′", title: "Ghép lại và so sánh", body: "Ba chu kỳ hoàn chỉnh rồi lặp quãng ban đầu bằng cùng tiêu chí." },
      { time: "05′", title: "Kết luận buổi tập", body: "Ghi điều đã cải thiện, tín hiệu cần giữ và nội dung chuyển sang buổi sau." },
    ],
    questions: [
      { q: "Nhận xét nào mô tả lỗi có thể quan sát rõ nhất?", options: ["Bơi chưa đẹp", "Kỹ thuật yếu", "Gối mở rộng hơn hông trong pha thu", "Cần cố gắng hơn"], answer: 2, explain: "Mô tả gối mở rộng gắn với một pha cụ thể nên có thể quan sát, kiểm tra và chọn bài tập sửa." },
      { q: "Khi người học có nhiều lỗi cùng lúc, nên ưu tiên thế nào?", options: ["Sửa tất cả trong một lượt", "Sửa lỗi an toàn trước rồi chọn một lỗi kỹ thuật chính", "Chỉ sửa lỗi làm bơi chậm", "Tăng quãng đường để tự thích nghi"], answer: 1, explain: "Lỗi an toàn phải được chặn trước; sau đó chỉ tập trung một lỗi chính để phản hồi có thể thực hiện được." },
      { q: "Trình tự sửa lỗi phù hợp là gì?", options: ["Bơi dài – nhận xét – bơi dài hơn", "Trên cạn – có điểm tựa – đoạn ngắn – ghép hoàn chỉnh", "Tăng tốc – quay phim – đổi kỹ thuật", "Chỉ xem lại đoạn ghi hình"], answer: 1, explain: "Giảm độ khó trước rồi ghép dần vào động tác hoàn chỉnh giúp người học cảm nhận và duy trì thay đổi." },
      { q: "Cách nào xác nhận một bài tập sửa có hiệu quả?", options: ["Người học thấy mệt hơn", "Bơi nhanh hơn ở một lượt bất kỳ", "So sánh cùng tiêu chí và quãng đường trước – sau", "Thực hiện càng nhiều bài tập càng tốt"], answer: 2, explain: "Giữ tương đối giống tiêu chí, góc quan sát và quãng đường giúp đánh giá thay đổi kỹ thuật đáng tin cậy hơn." },
      { q: "Góc quan sát phía sau phù hợp nhất để kiểm tra nội dung nào?", options: ["Sự đối xứng của tay, gối và bàn chân", "Thời điểm miệng hít vào", "Độ dài toàn bộ quãng bơi", "Mức độ mệt sau buổi tập"], answer: 0, explain: "Góc phía sau giúp nhìn rõ hai bên có chuyển động cân xứng hay không, đặc biệt ở tay, gối và bàn chân." },
      { q: "Phản hồi nào phù hợp sau một lượt ba chu kỳ?", options: ["Liệt kê toàn bộ lỗi đã thấy", "Đưa một tín hiệu ngắn gắn với lỗi ưu tiên", "Yêu cầu bơi nhanh hơn", "Đổi ngay sang ba bài tập khác"], answer: 1, explain: "Một tín hiệu ngắn giúp người học tập trung và cho phép đánh giá tín hiệu đó có làm giảm biểu hiện sai hay không." },
      { q: "Vì sao cần kiểm tra một nguyên nhân chính thay vì kết luận ngay?", options: ["Vì một biểu hiện có thể xuất phát từ nhiều nguyên nhân", "Vì mọi lỗi đều do thiếu sức mạnh", "Vì đoạn ghi hình luôn không chính xác", "Vì không cần quan sát kỹ thuật"], answer: 0, explain: "Cùng một biểu hiện có thể có nhiều nguyên nhân; thử một giả thuyết bằng tín hiệu và bài tập cụ thể giúp tránh sửa sai hướng." },
      { q: "Nếu một bài tập sửa gây đau khớp, nên làm gì?", options: ["Lặp đủ số lần rồi mới dừng", "Giảm nghỉ để hoàn thành nhanh", "Dừng bài gây đau và nhờ người có chuyên môn kiểm tra", "Tăng biên độ để khớp quen dần"], answer: 2, explain: "Đau là tín hiệu phải dừng; không được dùng số lần lặp làm lý do tiếp tục một bài tập có nguy cơ gây hại." },
      { q: "Sau ba lượt, biểu hiện sai không giảm. Bước tiếp theo phù hợp là gì?", options: ["Thêm nhiều khẩu lệnh cùng lúc", "Xem lại giả thuyết nguyên nhân và đổi tín hiệu hoặc bài tập", "Tăng quãng lên 50 m", "Bỏ bước đánh giá lại"], answer: 1, explain: "Nếu biểu hiện không thay đổi, cần xem lại giả thuyết hoặc cách sửa; chồng thêm khẩu lệnh chỉ làm khó xác định yếu tố nào có tác dụng." },
      { q: "Bản ghi trước – sau nào có giá trị nhất?", options: ["Hai quãng khác nhau ở hai góc khác nhau", "Cùng góc, cùng quãng và cùng một dấu hiệu quan sát", "Một lượt chậm và một lượt nước rút", "Chỉ ghi cảm giác của người bơi"], answer: 1, explain: "Giữ cùng điều kiện quan sát và tiêu chí chính giúp so sánh mức thay đổi của đúng lỗi đang sửa." },
    ],
    memory: "Nhìn đúng biểu hiện – ưu tiên một lỗi – thử một tín hiệu – sửa theo bậc – đo lại cùng tiêu chí.",
  },
  "08": {
    safety: {
      title: "Kế hoạch không thay thế người giám sát",
      body: "Mỗi buổi vẫn phải tập tại khu vực được phép, có bạn tập hoặc người giám sát đủ năng lực và biết rõ lối ra. Không tự tăng quãng đường khi đau, chóng mặt, khó thở, chuột rút hoặc kỹ thuật mất kiểm soát; dừng, bám thành và hồi phục trước khi quyết định có tập tiếp hay không.",
    },
    knowledge: [
      {
        title: "Khóa điểm xuất phát",
        body: "Kế hoạch chỉ có ý nghĩa khi người học biết mình đang làm tốt điều gì và cần sửa điều gì trước buổi đầu tiên.",
        steps: ["Bơi một lượt ngắn 10–25 m trong điều kiện an toàn.", "Ghi quãng đường, số chu kỳ và mức kiểm soát hô hấp.", "Chọn đúng một lỗi kỹ thuật ưu tiên cho tuần đầu."],
        cue: "Đo trước · chọn một lỗi · rồi mới lập kế hoạch",
        avoid: "Không lấy tốc độ hoặc cảm giác mệt làm thước đo duy nhất.",
      },
      {
        title: "Cấu trúc một buổi tập",
        body: "Một buổi 45–60 phút cần có phần chuẩn bị, kỹ thuật trọng tâm, ghép nhịp, đánh giá ngắn và hồi tĩnh.",
        steps: ["Khởi động trên bờ và kiểm tra khu vực tập.", "Ôn một kỹ thuật riêng bằng đoạn ngắn có nghỉ.", "Ghép vào bơi hoàn chỉnh rồi ghi kết quả cuối buổi."],
        cue: "Làm ấm · sửa một việc · ghép lại · ghi chép",
        avoid: "Không bơi liên tục từ đầu đến cuối mà thiếu mục tiêu kỹ thuật.",
      },
      {
        title: "Tuần 1 · Nền tảng và đường thân",
        body: "Ưu tiên an toàn, nhịp thở, tư thế lướt và khả năng kết thúc mỗi lượt bơi trong kiểm soát.",
        steps: ["Ôn thổi khí, nổi và đứng dậy an toàn.", "Lướt 3–5 m với đầu, hông và chân cùng trục.", "Kết thúc bằng các đoạn 5–10 m nhẹ, không chạy theo tốc độ."],
        cue: "Bình tĩnh · thân dài · kết thúc chủ động",
        avoid: "Không chuyển sang bơi dài khi đầu còn ngẩng cao hoặc hô hấp chưa đều.",
      },
      {
        title: "Tuần 2 · Chân, tay và thở riêng",
        body: "Củng cố từng mảnh kỹ thuật bằng quãng ngắn, nghỉ đủ và chỉ tăng khối lượng khi dấu hiệu đúng lặp lại ổn định.",
        steps: ["Tập chân với nhịp thu – bẻ – đạp khép – lướt.", "Tập tay với giới hạn không kéo quá vai.", "Ghép tay – thở thành tám chu kỳ đều."],
        cue: "Đúng hình trước · đủ số sau",
        avoid: "Không tăng số mét để bù cho động tác đang sai.",
      },
      {
        title: "Tuần 3 · Phối hợp hoàn chỉnh",
        body: "Ghép tay, thở, chân và lướt theo đúng trật tự; dùng các đoạn 10–25 m để giữ chất lượng đến cuối lượt.",
        steps: ["Nhắc nhịp quạt – thở – tay về – đạp – lướt.", "Bơi ba chu kỳ rồi tự nêu một dấu hiệu cần giữ.", "Tăng dần đến 25 m khi tay – chân không còn chồng lực."],
        cue: "Quạt – thở · tay dài – chân đạp · lướt",
        avoid: "Không rút ngắn pha lướt chỉ để tăng tần số động tác.",
      },
      {
        title: "Tuần 4 · Ổn định và đánh giá",
        body: "Giữ lại một tín hiệu sửa hiệu quả, giảm hỗ trợ và kiểm tra khả năng bơi 25 m với nhịp ổn định.",
        steps: ["So sánh cùng quãng và cùng tiêu chí với tuần đầu.", "Bơi hai đến ba lượt 25 m, nghỉ đủ giữa lượt.", "Ghi kết quả, lỗi còn lại và mục tiêu cho giai đoạn tiếp theo."],
        cue: "Cùng tiêu chí · cùng quãng · so trước sau",
        avoid: "Không coi một lượt nhanh nhưng sai kỹ thuật là kết quả đạt.",
      },
    ],
    drills: [
      { code: "8.1", title: "Buổi 1–2 · Nền tảng", goal: "Ổn định an toàn, hô hấp và tư thế lướt", steps: ["Thở tại thành", "Nổi rồi đứng dậy", "Lướt 3–5 m", "Bơi nhẹ 5–10 m"], volume: "Tuần 1 · 2 buổi", pass: "Lướt đúng trục và tự kết thúc an toàn", safety: "Luôn có người giám sát; không thi nín thở" },
      { code: "8.2", title: "Buổi 3–4 · Kỹ thuật riêng", goal: "Lặp đúng chân, tay và thở trước khi ghép", steps: ["Chân đoạn ngắn", "Tay có hỗ trợ", "Tay – thở tám nhịp", "Ghi một lỗi"], volume: "Tuần 2 · 2 buổi", pass: "Mỗi kỹ thuật đạt dấu hiệu đúng ở 4/5 lần", safety: "Dừng bài tập gây đau gối, vai hoặc hụt hơi" },
      { code: "8.3", title: "Buổi 5 · Ghép ba chu kỳ", goal: "Tách rõ thời điểm tạo lực của tay và chân", steps: ["Mô phỏng trên cạn", "Một chu kỳ – một lướt", "Ba chu kỳ liên tục", "Nhận xét một tín hiệu"], volume: "Tuần 3 · buổi đầu", pass: "Ba lượt không chồng lực tay – chân", safety: "Tập gần điểm bám và nghỉ sau mỗi lượt" },
      { code: "8.4", title: "Buổi 6 · Duy trì 10–25 m", goal: "Giữ nhịp đúng khi quãng đường tăng", steps: ["Hai lượt 10 m", "Hai lượt 15 m", "Một đến hai lượt 25 m", "Ghi số chu kỳ"], volume: "Tuần 3 · buổi sau", pass: "Có pha lướt rõ đến cuối ít nhất hai lượt", safety: "Giảm quãng ngay khi hô hấp hoặc tư thế mất kiểm soát" },
      { code: "8.5", title: "Buổi 7–8 · Sửa và đánh giá", goal: "Xác nhận tiến bộ bằng cùng tiêu chí đầu kỳ", steps: ["Sửa một lỗi ưu tiên", "Bơi thử 25 m", "Nghỉ đủ", "Lặp đánh giá và ghi kết quả"], volume: "Tuần 4 · 2 buổi", pass: "Hoàn thành 25 m đúng trình tự, hô hấp có kiểm soát", safety: "Không đánh giá khi cơ thể đau, quá mệt hoặc khu vực tập không bảo đảm" },
    ],
    mistakes: [
      { sign: "Tăng quãng đường dù kỹ thuật đang hỏng", cause: "Dùng số mét làm mục tiêu chính thay cho chất lượng động tác", fix: "Giảm về 5–10 m hoặc ba chu kỳ; chỉ tăng khi dấu hiệu đúng lặp lại ổn định." },
      { sign: "Buổi nào cũng sửa một nội dung khác", cause: "Không khóa lỗi ưu tiên và không theo dõi tác dụng của bài tập", fix: "Giữ một tín hiệu sửa trong ít nhất hai buổi rồi mới đánh giá giữ hay đổi." },
      { sign: "Nghỉ quá ít giữa các lượt", cause: "Muốn hoàn thành nhanh số mét đã đặt", fix: "Nghỉ đến khi hô hấp bình thường và có thể nhắc lại mục tiêu kỹ thuật của lượt sau." },
      { sign: "Chỉ ghi thời gian, không ghi chất lượng", cause: "Nhầm tốc độ với mức hoàn thiện kỹ thuật", fix: "Ghi thêm quãng đường, số chu kỳ, lỗi ưu tiên và dấu hiệu đúng đã duy trì." },
    ],
    session: [
      { time: "T1 · B1", title: "Đo điểm xuất phát", body: "Ôn an toàn, thở, lướt; ghi một lượt ngắn và chọn một lỗi ưu tiên." },
      { time: "T1 · B2", title: "Ổn định đường thân", body: "Lướt 3–5 m, đứng dậy đúng trình tự và bơi nhẹ các đoạn 5–10 m." },
      { time: "T2 · B3", title: "Củng cố kỹ thuật chân", body: "Thu – bẻ – đạp khép – lướt bằng các đoạn ngắn, nghỉ đủ sau mỗi lượt." },
      { time: "T2 · B4", title: "Củng cố tay và thở", body: "Giới hạn đường tay, hít đúng lúc và duy trì tám nhịp tay – thở liên tục." },
      { time: "T3 · B5", title: "Ghép ba chu kỳ", body: "Dùng nhịp đếm để tách tay và chân; kết thúc mỗi chu kỳ bằng tư thế dài." },
      { time: "T3 · B6", title: "Duy trì đến 25 m", body: "Tăng từ 10 m lên 25 m khi nhịp vẫn ổn; ghi số chu kỳ và chất lượng lướt." },
      { time: "T4 · B7", title: "Sửa lỗi cuối", body: "Chọn một lỗi còn lại, sửa theo bậc rồi bơi lại cùng quãng đánh giá." },
      { time: "T4 · B8", title: "Đánh giá cuối bốn tuần", body: "Bơi 25 m có kiểm soát, so với tuần đầu và khóa mục tiêu luyện tiếp theo." },
    ],
    questions: [
      { q: "Khi nào nên tăng quãng đường trong kế hoạch bốn tuần?", options: ["Sau mỗi buổi dù kỹ thuật thế nào", "Khi dấu hiệu đúng lặp lại ổn định và hô hấp vẫn kiểm soát", "Khi người học thấy mệt", "Chỉ khi bơi nhanh hơn"], answer: 1, explain: "Quãng đường chỉ nên tăng khi chất lượng động tác và hô hấp vẫn được duy trì, không phải chỉ vì đã hoàn thành đủ số buổi." },
      { q: "Một buổi tập 45–60 phút nên được tổ chức theo trình tự nào?", options: ["Bơi liên tục rồi kết thúc", "Đánh giá trước, bỏ khởi động, tăng tốc", "Khởi động – kỹ thuật trọng tâm – ghép nhịp – đánh giá – hồi tĩnh", "Chỉ tập lỗi khó nhất"], answer: 2, explain: "Cấu trúc này chuẩn bị cơ thể, tạo thời gian sửa một kỹ thuật, đưa kỹ thuật trở lại động tác hoàn chỉnh và ghi nhận kết quả." },
      { q: "Nếu kỹ thuật mất kiểm soát ở đoạn 25 m, lựa chọn phù hợp là gì?", options: ["Cố bơi hết bằng mọi giá", "Tăng tốc để kết thúc sớm", "Giảm về đoạn ngắn hoặc ba chu kỳ rồi khôi phục nhịp", "Bỏ phần nghỉ giữa lượt"], answer: 2, explain: "Giảm độ khó giúp người học lấy lại trình tự và hô hấp trước khi tăng quãng trở lại." },
      { q: "Bản ghi cuối buổi nào hữu ích nhất?", options: ["Chỉ tổng số mét", "Chỉ thời gian nhanh nhất", "Quãng đường, số chu kỳ, lỗi ưu tiên và dấu hiệu đúng", "Chỉ cảm giác mệt"], answer: 2, explain: "Bốn dữ kiện này cho biết cả khối lượng lẫn chất lượng kỹ thuật để điều chỉnh buổi tiếp theo." },
      { q: "Trọng tâm chính của tuần đầu tiên là gì?", options: ["Tăng tốc độ tối đa", "An toàn, hô hấp, đường thân và kết thúc lượt bơi có kiểm soát", "Chỉ tập sức mạnh chân", "Bơi 25 m liên tục ngay buổi đầu"], answer: 1, explain: "Tuần 1 khóa nền tảng an toàn, nhịp thở và đường thân trước khi tăng yêu cầu kỹ thuật hoặc quãng đường." },
      { q: "Tuần 2 nên củng cố chân, tay và thở theo cách nào?", options: ["Ghép tất cả ngay thành quãng dài", "Tập từng mảnh bằng đoạn ngắn, nghỉ đủ rồi mới ghép", "Chỉ xem lại lý thuyết", "Thay đổi kỹ thuật ở mỗi lượt"], answer: 1, explain: "Tách kỹ thuật thành các đoạn ngắn giúp lặp đúng hình động tác; chỉ ghép khi dấu hiệu đúng đã ổn định." },
      { q: "Khẩu lệnh nào đúng cho tuần phối hợp hoàn chỉnh?", options: ["Đạp – quạt – ngẩng – đạp", "Quạt – thở – tay về – đạp – lướt", "Thở – đạp – quạt – dừng", "Quạt và đạp cùng lúc liên tục"], answer: 1, explain: "Trình tự quạt – thở – tay về – đạp – lướt tách thời điểm tạo lực của tay và chân, đồng thời giữ được pha lướt." },
      { q: "Đánh giá cuối tuần 4 nên so sánh như thế nào?", options: ["Đổi quãng và đổi tiêu chí để dễ đạt", "Chỉ so thời gian nhanh nhất", "Dùng cùng quãng đường và cùng tiêu chí với tuần đầu", "Chỉ dựa vào cảm giác"], answer: 2, explain: "So sánh trong điều kiện và tiêu chí tương đương giúp xác định tiến bộ kỹ thuật rõ hơn." },
      { q: "Nếu xuất hiện đau, chóng mặt, khó thở hoặc chuột rút trong buổi tập, cần làm gì?", options: ["Cố hoàn thành nốt giáo án", "Tăng thời gian nín thở", "Dừng, bám điểm tựa, hồi phục và báo người giám sát", "Bơi nhanh về cuối bể"], answer: 2, explain: "Các dấu hiệu cảnh báo yêu cầu dừng tập và đưa cơ thể về trạng thái an toàn; giáo án không được dùng để ép tiếp tục." },
      { q: "Một tín hiệu sửa đã dùng qua hai buổi nhưng lỗi không giảm. Bước phù hợp là gì?", options: ["Thêm nhiều khẩu lệnh cùng lúc", "Giữ nguyên vô thời hạn", "Đánh giá lại nguyên nhân rồi đổi một tín hiệu hoặc bài tập", "Tăng gấp đôi quãng đường"], answer: 2, explain: "Khi một cách sửa không tạo thay đổi, cần kiểm tra lại giả thuyết nguyên nhân và thử một điều chỉnh mới có thể đo được." },
    ],
    memory: "Đo trước – tập đúng một trọng tâm – tăng quãng theo chất lượng – ghi lại – so cùng tiêu chí sau bốn tuần.",
    practiceEyebrow: "Kế hoạch bốn tuần",
    practiceTitle: "Tám buổi theo một nhịp tăng hợp lý",
    practiceText: "Mỗi tuần hai buổi là gợi ý. Có thể kéo dài lịch nếu chưa đạt dấu hiệu đúng; không ép tăng quãng chỉ để kịp thời gian.",
    sessionEyebrow: "Lịch triển khai",
    sessionTitle: "Tám buổi trong bốn tuần",
    sessionText: "Mỗi buổi 45–60 phút, tập trong điều kiện có giám sát và kết thúc bằng một dòng ghi chép có thể so sánh.",
  },
};

export const phases = [
  {
    id: "thu",
    number: "01",
    short: "Thu",
    title: "Thu chân",
    action: "Gót về gần mông, gối mở vừa phải.",
    purpose: "Tạo vị trí chuẩn bị với lực cản thấp.",
    cue: "Gót về · gối vừa · thân vẫn dài",
    avoid: "Không kéo đùi sâu về bụng hoặc mở gối quá rộng.",
  },
  {
    id: "be",
    number: "02",
    short: "Bẻ",
    title: "Bẻ bàn chân",
    action: "Gập cổ chân, xoay mũi chân ra ngoài.",
    purpose: "Tạo mặt tỳ nước trước khi đạp.",
    cue: "Gập cổ chân · mở mũi · tỳ nước",
    avoid: "Không giữ tư thế quá lâu hoặc đạp khi bàn chân chưa bẻ.",
  },
  {
    id: "dap",
    number: "03",
    short: "Đạp–khép",
    title: "Đạp và khép",
    action: "Đẩy nước ra sau, quét vào và khép kín.",
    purpose: "Tạo lực tiến chủ yếu cho chu kỳ.",
    cue: "Đẩy ra sau · quét vào · khép kín",
    avoid: "Không chỉ đạp rộng sang hai bên hoặc giật mạnh từ đầu.",
  },
  {
    id: "luot",
    number: "04",
    short: "Duỗi–lướt",
    title: "Duỗi chân và lướt",
    action: "Chân khép, mũi chân duỗi, thân thuôn dài.",
    purpose: "Giữ vận tốc và chuẩn bị chu kỳ mới.",
    cue: "Khép · dài · lướt",
    avoid: "Không gập gối lại quá sớm hoặc lướt đến khi gần dừng.",
  },
];

export const mistakes = [
  {
    id: "loi-goi-rong",
    name: "Gối mở quá rộng",
    sign: "Gối tách xa hông trong pha thu.",
    cause: "Thu chân bằng cách kéo hai gối sang ngang.",
    fix: "Giữ gối gần bề rộng hông; đưa gót về sau.",
    drill: "Mô phỏng chậm trên cạn với một vật mỏng giữa đùi.",
  },
  {
    id: "loi-goi-sau",
    name: "Gối kéo quá sâu",
    sign: "Đùi gập mạnh về bụng, hông dễ chìm.",
    cause: "Ưu tiên kéo gối về trước thay vì đưa gót về sau.",
    fix: "Giữ hông cao; giới hạn biên độ của gối.",
    drill: "Bám thành bể và tập thu gót có người quan sát.",
  },
  {
    id: "loi-ban-chan",
    name: "Bàn chân không bẻ",
    sign: "Mũi chân chúc thẳng ra sau khi bắt đầu đạp.",
    cause: "Cổ chân thả lỏng hoặc chuyển pha quá vội.",
    fix: "Gập cổ chân và mở mũi trước khi tạo lực.",
    drill: "Ngồi trên thành bể, tập bẻ hai bàn chân đồng thời.",
  },
  {
    id: "loi-huong-luc",
    name: "Đạp sang hai bên",
    sign: "Chân mở rộng nhưng cơ thể tiến rất ít.",
    cause: "Thiếu hướng đẩy nước ra sau.",
    fix: "Đẩy ra sau trước, sau đó mới quét vào và khép.",
    drill: "Đạp nằm ngửa để nhìn rõ đường đi của gối và bàn chân.",
  },
  {
    id: "loi-lech-nhip",
    name: "Hai chân lệch nhịp",
    sign: "Một chân bẻ hoặc kết thúc sớm hơn chân còn lại.",
    cause: "Phối hợp hai bên chưa ổn định.",
    fix: "Thu và kết thúc cùng lúc theo nhịp đếm chậm.",
    drill: "Ghi hình từ phía sau; tập chậm có đếm nhịp.",
  },
  {
    id: "loi-khong-luot",
    name: "Không có pha lướt",
    sign: "Gập gối lại ngay sau khi khép chân.",
    cause: "Nôn nóng bắt đầu chu kỳ mới.",
    fix: "Giữ thân dài một nhịp sau khi khép.",
    drill: "Một cú đạp, lướt đến mốc nhìn thấy trên thành bể.",
  },
];

export const practice = [
  { code: "6.1", name: "Mô phỏng trên cạn", volume: "2 lượt × 8 chu kỳ", goal: "Nhớ đúng hình dạng bốn pha", safety: "Có người giữ ổn định thân" },
  { code: "6.2", name: "Ngồi bẻ bàn chân", volume: "2 lượt × 10 lần", goal: "Bẻ cổ chân đồng thời", safety: "Không ép xoay khi đau gối" },
  { code: "6.3", name: "Bám thành bể", volume: "3 lượt × 8 lần", goal: "Gót về, gối vừa, đạp–khép", safety: "Thở thoải mái, nghỉ giữa lượt" },
  { code: "6.4", name: "Đạp nằm ngửa", volume: "4 lượt × 10 m", goal: "Quan sát độ rộng gối", safety: "Luôn giữ mặt trên nước" },
  { code: "6.5", name: "Đạp chân với ván", volume: "4 lượt × 15–25 m", goal: "Tạo lực tiến và nhịp lướt", safety: "Không ngẩng đầu liên tục" },
  { code: "6.6", name: "Một đạp – một lướt", volume: "6 lần × 5–8 m", goal: "Khép kín và kéo dài pha lướt", safety: "Thực hiện gần thành bể" },
];

export const sessionPlan = [
  { time: "10′", title: "Khởi động", body: "Làm ấm hông, gối, cổ chân; nhắc lại quy tắc an toàn." },
  { time: "08′", title: "Ôn trên cạn", body: "Mô phỏng bốn pha, ưu tiên sửa gối và bàn chân." },
  { time: "08′", title: "Bám thành", body: "Thu – bẻ – đạp khép – lướt; hai chân đồng thời." },
  { time: "18′", title: "Di chuyển", body: "Đạp nằm ngửa và đạp với ván; quan sát hướng tiến." },
  { time: "10′", title: "Ứng dụng", body: "Một cú đạp – một lướt; ghi hình ngắn nếu có." },
  { time: "06′", title: "Hồi tĩnh", body: "Thả lỏng, ổn định nhịp thở và chọn một lỗi cần sửa." },
];

export const questions = [
  {
    q: "Pha nào tạo vị trí thuận lợi để bắt đầu tạo lực?",
    options: ["Thu chân", "Lướt", "Khép chân", "Nổi sấp"],
    answer: 0,
    explain: "Pha thu tạo vị trí cơ học thuận lợi để bàn chân chuẩn bị tỳ nước.",
  },
  {
    q: "Tín hiệu đúng nhất ở cuối pha bẻ bàn chân là gì?",
    options: ["Mũi chân chúc thẳng ra sau", "Cổ chân gập, mũi chân mở ra ngoài", "Hai gối ép sát tuyệt đối", "Đùi kéo sâu vào bụng"],
    answer: 1,
    explain: "Cổ chân gập và mũi chân mở giúp tạo mặt tỳ trong phần đầu pha đạp.",
  },
  {
    q: "Vì sao pha thu cần gọn và tương đối thư giãn?",
    options: ["Để tăng thời gian nghỉ", "Để giảm lực cản và chuẩn bị đạp", "Để đầu nổi cao", "Để tay quạt rộng hơn"],
    answer: 1,
    explain: "Pha thu không tạo lực tiến đáng kể nên phải gọn để hạn chế mất tốc độ.",
  },
  {
    q: "Trong pha tạo lực, hướng nước ưu tiên là gì?",
    options: ["Ra trước", "Lên trên", "Ra sau, kết hợp quét vào trong", "Chỉ sang hai bên"],
    answer: 2,
    explain: "Đẩy nước ra sau tạo phản lực đưa cơ thể về trước; đường quét giúp khép chân.",
  },
  {
    q: "Khi nào pha lướt kết thúc hợp lý?",
    options: ["Ngay sau khi hai chân khép", "Khi cơ thể đã dừng hẳn", "Trước khi vận tốc giảm quá nhiều", "Sau hai nhịp thở"],
    answer: 2,
    explain: "Lướt quá ngắn làm lãng phí vận tốc, còn quá dài khiến cơ thể mất nhịp.",
  },
  {
    q: "Lỗi nào thường làm lực cản tăng mạnh khi thu chân?",
    options: ["Gót về gần mông", "Gối mở quá rộng và kéo sâu", "Bàn chân bẻ ra ngoài", "Hai chân khép sau đạp"],
    answer: 1,
    explain: "Gối mở rộng và kéo sâu làm tăng diện tích cản phía trước, đồng thời khiến hông dễ chìm.",
  },
  {
    q: "Theo nguyên tắc kỹ thuật hiện hành, chuyển động hai chân phải thế nào?",
    options: ["Luân phiên", "Đồng thời, không xen kẽ", "Một chân trước, một chân sau", "Tùy từng người bơi"],
    answer: 1,
    explain: "Hai chân phải chuyển động đồng thời, không được thực hiện xen kẽ.",
  },
  {
    q: "Nếu xuất hiện đau mặt trong gối khi đạp, hành động phù hợp nhất là gì?",
    options: ["Cố đạp mạnh hơn", "Tăng biên độ", "Dừng bài tập gây đau và nhờ kiểm tra", "Khóa cứng cổ chân"],
    answer: 2,
    explain: "Đau là tín hiệu phải giảm tải và kiểm tra, không phải mục tiêu cần vượt qua bằng sức.",
  },
  {
    q: "Bài tập nào giúp quan sát độ rộng gối rõ nhất?",
    options: ["Đạp nằm ngửa", "Bơi sải", "Nín thở dưới nước", "Quạt tay tại chỗ"],
    answer: 0,
    explain: "Khi đạp nằm ngửa, người học dễ nhìn đường đi của gối và bàn chân.",
  },
  {
    q: "Khẩu lệnh đầy đủ cho cả chu kỳ là gì?",
    options: ["Thu – bẻ – đạp khép – lướt", "Quạt – thở – kéo – nghỉ", "Gối – tay – đầu – chân", "Nhanh – mạnh – rộng – dừng"],
    answer: 0,
    explain: "Khẩu lệnh này phản ánh đúng thứ tự bốn pha của động tác chân.",
  },
];
