"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { connectAdminDevice, roleLabels, upstreamJson, type AdminAccess, type AdminBootstrap, type ControlRole } from "./admin-device-client";
import styles from "./health-admin.module.css";

type HealthStatus = "permission_requested" | "draft" | "review" | "published" | "changes_requested" | "denied" | "cancelled" | "archived";
type HealthVersion = { id:string; version_number:number; status:HealthStatus; summary:string|null; created_by:string; editor_device_code?:string|null; edit_scope?:string|null; edit_scope_label?:string|null; permission_note?:string|null; submitted_at?:string|null; published_at?:string|null; created_at:string; updated_at:string };
type HealthDevice = { deviceId:string; deviceCode:string; status:"pending"|"approved"|"blocked"; deviceType:"desktop"|"phone"|"tablet"; platform:string|null; browser:string|null; screenWidth:number|null; screenHeight:number|null; label:string|null; editEnabled:boolean; calendarEnabled:boolean; createdAt:string; approvedAt:string|null; blockedAt:string|null; lastSeenAt:string; lastActivityAt:string; offlineSinceAt:string|null; active:boolean };
type ContentData = { application:"child-health"; versions:HealthVersion[]; versionId?:string; editScope?:{label:string}; currentSection?:unknown; proposedSection?:unknown; validationErrors?:string[] };
type DeviceData = { application:"child-health"; devices:HealthDevice[] };
type Tab = "overview"|"devices"|"review"|"versions";
type Filter = "all"|"pending"|"approved"|"blocked"|"desktop"|"phone"|"tablet";

const statusLabels:Record<HealthStatus,string>={permission_requested:"Xin quyền",draft:"Bản nháp",review:"Chờ duyệt",published:"Đang xuất bản",changes_requested:"Cần sửa lại",denied:"Từ chối",cancelled:"Đã hủy",archived:"Lưu trữ"};
const deviceTypeLabels={desktop:"Máy tính",phone:"Điện thoại",tablet:"Máy tính bảng / iPad"} as const;
const deviceStatusLabels={pending:"Chờ duyệt",approved:"Được truy cập",blocked:"Đã khóa"} as const;

function formatDate(value?:string|null){if(!value)return"—";const d=new Date(value);return Number.isFinite(d.getTime())?new Intl.DateTimeFormat("vi-VN",{dateStyle:"short",timeStyle:"short"}).format(d):"—";}
function canReview(role:ControlRole){return["reviewer","publisher","owner"].includes(role)}
function canPublish(role:ControlRole){return["publisher","owner"].includes(role)}
function deviceActionMessage(action:string){if(action==="approve")return"Đã cấp quyền truy cập.";if(action==="block")return"Đã khóa thiết bị và thu hồi các quyền tính năng.";if(action==="unblock")return"Đã mở khóa thiết bị.";if(action==="enable-edit")return"Đã cấp quyền chỉnh sửa trên thiết bị.";if(action==="disable-edit")return"Đã thu hồi quyền chỉnh sửa.";if(action==="enable-calendar")return"Đã cấp quyền Google Calendar cho thiết bị.";if(action==="disable-calendar")return"Đã thu hồi quyền Google Calendar.";return"Đã cập nhật thiết bị."}

function Gate({access,busy,error,retry}:{access:AdminAccess|null;busy:boolean;error:string;retry:()=>void}){return <main className={styles.gate}><section><span className={styles.eyebrow}>Sức khỏe Y tế · quản trị riêng</span><h1>{access?.status==="pending"?"Thiết bị quản trị đang chờ cấp quyền.":access?.status==="blocked"?"Thiết bị quản trị đã bị khóa.":"Đang xác thực quản trị…"}</h1><p>{error||"Danh tính quản trị do Trung tâm cấp; thiết bị người dùng và dữ liệu vận hành vẫn do Sức khỏe Y tế quản lý độc lập."}</p>{access?.deviceCode?<div className={styles.code}><span>Mã thiết bị quản trị</span><strong>{access.deviceCode}</strong></div>:null}<button className={styles.primary} onClick={retry} disabled={busy}>{busy?"Đang kiểm tra…":"Kiểm tra lại"}</button></section></main>}

export default function HealthControlCenter({user}:{user:{displayName:string;email:string}}){
 const[access,setAccess]=useState<AdminAccess|null>(null);const[bootstrap,setBootstrap]=useState<AdminBootstrap|null>(null);const[versions,setVersions]=useState<HealthVersion[]>([]);const[devices,setDevices]=useState<HealthDevice[]>([]);const[selectedId,setSelectedId]=useState("");const[currentSection,setCurrentSection]=useState<unknown>(null);const[proposedSection,setProposedSection]=useState<unknown>(null);const[scopeLabel,setScopeLabel]=useState("");const[tab,setTab]=useState<Tab>("overview");const[filter,setFilter]=useState<Filter>("all");const[note,setNote]=useState("");const[busy,setBusy]=useState(true);const[error,setError]=useState("");const[notice,setNotice]=useState("");
 async function loadContent(bridge:AdminBootstrap["boiBridge"]){const data=await upstreamJson<ContentData>(bridge,"/api/control/health-content");setVersions(data.versions??[]);return data.versions??[]}
 async function loadDevices(bridge:AdminBootstrap["boiBridge"]){const data=await upstreamJson<DeviceData>(bridge,"/api/control/devices");setDevices(data.devices??[]);return data.devices??[]}
 async function initialize(){setBusy(true);setError("");try{const result=await connectAdminDevice("child-health");setAccess(result.access);setBootstrap(result.bootstrap);if(result.access.status==="approved"&&result.bootstrap&&canReview(result.access.role)){await Promise.all([loadContent(result.bootstrap.boiBridge),loadDevices(result.bootstrap.boiBridge)])}}catch(caught){setError(caught instanceof Error?caught.message:"Không thể mở quản trị Sức khỏe Y tế.")}finally{setBusy(false)}}
 useEffect(()=>{void initialize()},[]);
 const counts=useMemo(()=>({pending:devices.filter(x=>x.status==="pending").length,online:devices.filter(x=>x.active).length,edit:devices.filter(x=>x.editEnabled).length,calendar:devices.filter(x=>x.calendarEnabled).length,review:versions.filter(x=>x.status==="permission_requested"||x.status==="review").length}),[devices,versions]);
 const visibleDevices=devices.filter(d=>filter==="all"||(filter==="desktop"||filter==="phone"||filter==="tablet"?d.deviceType===filter:d.status===filter));
 const reviewVersions=versions.filter(x=>["permission_requested","review","changes_requested"].includes(x.status));const selected=versions.find(x=>x.id===selectedId)??null;
 async function selectVersion(id:string){if(!bootstrap)return;setBusy(true);setError("");setSelectedId(id);try{const data=await upstreamJson<ContentData>(bootstrap.boiBridge,"/api/control/health-content",{query:`?versionId=${encodeURIComponent(id)}`});setVersions(data.versions??[]);setCurrentSection(data.currentSection??null);setProposedSection(data.proposedSection??null);setScopeLabel(data.editScope?.label??"")}catch(caught){setError(caught instanceof Error?caught.message:"Không thể tải phiên bản.")}finally{setBusy(false)}}
 async function contentAction(action:string,success:string,id=selectedId){if(!bootstrap||!id)return;setBusy(true);setError("");setNotice("");try{const data=await upstreamJson<ContentData>(bootstrap.boiBridge,"/api/control/health-content",{method:"POST",body:{action,versionId:id,note}});setVersions(data.versions??[]);setNotice(success);setNote("");if(data.versionId)setSelectedId(data.versionId);if(action==="approve-publish"||action==="rollback"||action==="cancel"||action==="deny-edit"){setCurrentSection(null);setProposedSection(null);setScopeLabel("")}else await selectVersion(data.versionId??id)}catch(caught){setError(caught instanceof Error?caught.message:"Không thể thực hiện thao tác.")}finally{setBusy(false)}}
 async function deviceAction(device:HealthDevice,action:string){if(!bootstrap)return;setBusy(true);setNotice("");setError("");try{const data=await upstreamJson<DeviceData>(bootstrap.boiBridge,"/api/control/devices",{method:"POST",body:{action,deviceId:device.deviceId}});setDevices(data.devices??[]);setNotice(deviceActionMessage(action))}catch(caught){setError(caught instanceof Error?caught.message:"Không thể cập nhật thiết bị.")}finally{setBusy(false)}}
 if(!access||access.status!=="approved"||!bootstrap)return <Gate access={access} busy={busy} error={error} retry={()=>void initialize()}/>;
 const applicationUrl=`${bootstrap.boiBridge.baseUrl}/suc-khoe-tre`;const editorUrl=`${bootstrap.boiBridge.baseUrl}/api/editor/session?ticket=${encodeURIComponent(bootstrap.boiBridge.token)}`;
 return <main className={styles.shell}><div className={styles.frame}><Link href="/" className={styles.back}>← Trung tâm quản trị ứng dụng</Link><header className={styles.header}><div><span>Ứng dụng hoạt động độc lập</span><h1>Quản trị Sức khỏe Y tế</h1><p>Quản lý thiết bị truy cập, quyền tính năng và nội dung của riêng Sức khỏe Y tế. Trung tâm không chứa hồ sơ sức khỏe cá nhân.</p></div><div className={styles.actions}><a className={styles.secondary} href={applicationUrl} target="_blank" rel="noreferrer">Mở ứng dụng</a><a className={styles.secondary} href={editorUrl} target="_blank" rel="noreferrer">Mở trình biên tập</a></div></header><div className={styles.boundary}><strong>Ranh giới:</strong> Thiết bị Sức khỏe Y tế có mã SK riêng và dữ liệu riêng. Trung tâm chỉ cấp/thu hồi quyền; hồ sơ, số đo, checklist và nhật ký cá nhân không được chuyển về đây.</div>{error?<div className={styles.error}>{error}</div>:null}{notice?<div className={styles.notice}>{notice}</div>:null}
 <section className={styles.summary}><article><span>Chờ cấp quyền</span><strong>{counts.pending}</strong><small>Thiết bị SK mới</small></article><article><span>Đang online</span><strong>{counts.online}</strong><small>Tín hiệu ký gần nhất</small></article><article><span>Quyền tính năng</span><strong>{counts.edit}/{counts.calendar}</strong><small>Sửa / Google Calendar</small></article><article><span>Việc nội dung</span><strong>{counts.review}</strong><small>Xin quyền hoặc chờ duyệt</small></article></section>
 <nav className={styles.tabs}>{([['overview','Tổng quan'],['devices','Thiết bị & truy cập'],['review','Duyệt nội dung'],['versions','Lịch sử phiên bản']] as const).map(([id,label])=><button key={id} className={`${styles.tab} ${tab===id?styles.active:""}`} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {tab==="overview"?<section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>Phân bổ đúng chức năng</span><h2>Mỗi nhóm quản trị chỉ giữ dữ liệu cần thiết</h2><p>Thiết bị: cấp/khóa truy cập, quyền sửa và Google Calendar. Nội dung: duyệt bản sửa. Dữ liệu sức khỏe cá nhân: không chuyển về quản trị.</p></div><div><strong>{user.displayName}</strong><br/><small>{roleLabels[access.role]} · {access.deviceCode}</small></div></div><div className={styles.bar}><button className={styles.primary} onClick={()=>setTab("devices")}>Quản lý thiết bị ({devices.length})</button><button className={styles.secondary} onClick={()=>{setTab("review");const first=reviewVersions[0];if(first)void selectVersion(first.id)}}>Hàng đợi nội dung ({reviewVersions.length})</button><button className={styles.secondary} onClick={()=>void initialize()} disabled={busy}>Cập nhật toàn bộ</button></div></section>:null}
 {tab==="devices"?<section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>Thiết bị đầu vào</span><h2>Nhận diện và cấp quyền theo thiết bị</h2><p>Phân loại tự động theo máy tính, điện thoại hoặc máy tính bảng/iPad. Quyền sửa và Google Calendar được cấp riêng, không tự bật ở Web App.</p></div></div><div className={styles.deviceFilters}>{([['all','Tất cả'],['pending','Chờ duyệt'],['approved','Được truy cập'],['blocked','Đã khóa'],['desktop','Máy tính'],['phone','Điện thoại'],['tablet','Tablet/iPad']] as const).map(([id,label])=><button key={id} data-active={filter===id} onClick={()=>setFilter(id)}>{label}</button>)}</div><div className={styles.deviceList}>{visibleDevices.map(device=><article key={device.deviceId} className={`${styles.device} ${device.status==="pending"?styles.pending:""}`}><div className={styles.identity}><strong>{device.label||device.deviceCode}</strong><span className={styles.deviceType}>{deviceTypeLabels[device.deviceType]}</span><small>{device.deviceCode} · {device.platform||"Nền tảng chưa rõ"} · {device.browser||"Trình duyệt chưa rõ"}</small></div><div className={styles.facts}><label>Truy cập</label><strong>{deviceStatusLabels[device.status]}</strong><small className={device.active?styles.online:""}>{device.active?"Online":`Cuối ${formatDate(device.lastSeenAt)}`}</small></div><div className={styles.facts}><label>Quyền tính năng</label><strong>Sửa: {device.editEnabled?"Có":"Không"}</strong><small>Calendar: {device.calendarEnabled?"Được cấp":"Khóa"} · {device.screenWidth&&device.screenHeight?`${device.screenWidth}×${device.screenHeight}`:"Không có kích thước"}</small></div><div className={styles.deviceActions}>{canPublish(access.role)?<>{device.status==="pending"?<button className={styles.primary} disabled={busy} onClick={()=>void deviceAction(device,"approve")}>Cấp truy cập</button>:null}{device.status==="approved"?<><button className={styles.secondary} disabled={busy} onClick={()=>void deviceAction(device,device.editEnabled?"disable-edit":"enable-edit")}>{device.editEnabled?"Thu quyền sửa":"Cấp quyền sửa"}</button><button className={styles.secondary} disabled={busy} onClick={()=>void deviceAction(device,device.calendarEnabled?"disable-calendar":"enable-calendar")}>{device.calendarEnabled?"Khóa Calendar":"Cấp Calendar"}</button><button className={styles.danger} disabled={busy} onClick={()=>void deviceAction(device,"block")}>Khóa</button></>:null}{device.status==="blocked"?<button className={styles.secondary} disabled={busy} onClick={()=>void deviceAction(device,"unblock")}>Mở khóa</button>:null}</>:<small>Chỉ xem</small>}</div></article>)}{visibleDevices.length===0?<div className={styles.empty}>Không có thiết bị phù hợp bộ lọc.</div>:null}</div></section>:null}
 {tab==="review"?<section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>Kiểm duyệt riêng</span><h2>Yêu cầu chỉnh sửa Sức khỏe Y tế</h2></div></div><div className={styles.versionList}>{reviewVersions.map(v=><button className={styles.version} data-active={selectedId===v.id} key={v.id} onClick={()=>void selectVersion(v.id)}><span>{statusLabels[v.status]}</span><span><strong>V{v.version_number} · {v.edit_scope_label??v.edit_scope??"Nội dung"}</strong><small>{v.created_by} · {formatDate(v.updated_at)}</small></span><span>{v.editor_device_code??"—"}</span></button>)}{reviewVersions.length===0?<div className={styles.empty}>Không có yêu cầu nội dung chờ xử lý.</div>:null}</div>{selected?<><div className={styles.review}><article><h3>Bản đang xuất bản {scopeLabel?`· ${scopeLabel}`:""}</h3><pre>{currentSection==null?"Chưa có dữ liệu đối chiếu.":JSON.stringify(currentSection,null,2)}</pre></article><article><h3>Bản đề xuất</h3><pre>{proposedSection==null?"Chưa có nội dung đề xuất.":JSON.stringify(proposedSection,null,2)}</pre></article></div><textarea className={styles.note} value={note} onChange={e=>setNote(e.target.value)} placeholder="Ghi chú kiểm duyệt…" maxLength={1000}/><div className={styles.bar}>{selected.status==="permission_requested"&&canReview(access.role)?<><button className={styles.primary} disabled={busy} onClick={()=>void contentAction("approve-edit","Đã cho phép chỉnh sửa.")}>Cho phép sửa</button><button className={styles.danger} disabled={busy} onClick={()=>void contentAction("deny-edit","Đã từ chối yêu cầu.")}>Từ chối</button></>:null}{selected.status==="review"&&canReview(access.role)?<button className={styles.secondary} disabled={busy} onClick={()=>void contentAction("request-changes","Đã yêu cầu sửa lại.")}>Yêu cầu sửa lại</button>:null}{selected.status==="review"&&canPublish(access.role)?<button className={styles.primary} disabled={busy||selected.created_by===access.email} onClick={()=>void contentAction("approve-publish","Đã xuất bản nội dung.")}>Phê duyệt & xuất bản</button>:null}{["permission_requested","draft","changes_requested","review"].includes(selected.status)&&canReview(access.role)?<button className={styles.danger} disabled={busy} onClick={()=>void contentAction("cancel","Đã hủy phiên bản.")}>Hủy</button>:null}</div></>:null}</section>:null}
 {tab==="versions"?<section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>Lịch sử</span><h2>Phiên bản nội dung</h2><p>Rollback chỉ áp dụng cho phiên bản từng được xuất bản.</p></div></div><div className={styles.versionList}>{versions.map(v=><article className={styles.version} key={v.id}><span>{statusLabels[v.status]}</span><span><strong>V{v.version_number} · {v.summary||v.edit_scope_label||"Sức khỏe Y tế"}</strong><small>{v.created_by} · {formatDate(v.updated_at)}</small></span><span>{canPublish(access.role)&&["archived","published"].includes(v.status)?<button className={styles.secondary} disabled={busy||v.status==="published"} onClick={()=>void contentAction("rollback",`Đã khôi phục từ V${v.version_number}.`,v.id)}>Khôi phục</button>:formatDate(v.published_at)}</span></article>)}</div></section>:null}
 </div></main>
}
